Rewrote Integrating with Hardhat tutorial
foundry-rs/book pull request #1050
Opened 2023-11-20 21:35 UTC by Genesis3800

fixes #1033 

Was assigned this issue by @Evalir .
The updated tutorial will show folks how to create a combined Foundry + Hardhat project using the latest Hardhat-foundry plugin.

Included both scenarios:

1.  Adding Hardhat to a Foundry project
2.  Adding Foundry to a Hardhat project

Also linked a basic template in the article, I am open to transferring the ownership if you want. My basic template in turn links to [https://github.com/pcaversaccio/hardhat-project-template-ts](https://github.com/pcaversaccio/hardhat-project-template-ts) for anyone who wants a more in-depth template.

Tried to maintain as much resemblance to the OG article as possible.

2023-11-21 00:39 UTC, Evalir commented
Sick! will review soon—looping in @mds1 who has historical context on this

2023-11-22 02:27 UTC, mds1 commented
I've never actually setup a hardhat-foundry repo so I'm probably not the best person to review this unfortunately—@fvictorio by any chance you have the bandwidth to review for accuracy?

2023-11-23 11:26 UTC, fvictorio commented
Sure, I'll try to review this today/tomorrow!

2023-11-23 12:35 UTC, Genesis3800 commented
> Sure, I'll try to review this today/tomorrow!

Thanks a lot @fvictorio . I'll be really grateful to you for helping me gather some open source cred.

2023-11-24 11:18 UTC, fvictorio commented on src/config/hardhat.md
> +[Enjoy!](https://github.com/Genesis3800/HardhatInFoundry)
Should this be moved to the `foundry-rs` org?

2023-11-24 11:18 UTC, fvictorio commented on src/config/hardhat.md
> +4. `npm i --save-dev @nomicfoundation/hardhat-foundry @nomicfoundation/hardhat-toolbox` - This will install the Hardhat-foundry plugin and the Hardhat toolbox plugin which is a combination of all the
Very minor, but we normally lowercase the plugins, so it should be `hardhat-foundry` instead of `Hardhat-foundry`. Same for the other mentions of the plugin in the rest of the doc.

2023-11-24 11:18 UTC, fvictorio commented on src/config/hardhat.md
> +};
The config type import has to be placed before the config. 

```suggestion
require("@nomicfoundation/hardhat-toolbox");
require("@nomicfoundation/hardhat-foundry");

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  solidity: "0.8.19",
};
```

2023-11-24 11:18 UTC, fvictorio commented on src/config/hardhat.md
> +const { expect } = require("chai");
I recommend formatting this snippet with prettier

2023-11-24 11:20 UTC, fvictorio commented
The example repository has a couple of directories that shouldn't be committed: `artifacts` and `cache_hardhat`.

2023-11-24 13:13 UTC, Genesis3800 commented on src/config/hardhat.md
> +[Enjoy!](https://github.com/Genesis3800/HardhatInFoundry)
@Evalir I'll push a new commit in a few hours, but just for this, I wanted to let you know that I am open to transferring the repo.

Lemme know if you guys want it transferred after I make the changes Victorio asked for.

2023-11-24 19:18 UTC, Genesis3800 commented on src/config/hardhat.md
> +4. `npm i --save-dev @nomicfoundation/hardhat-foundry @nomicfoundation/hardhat-toolbox` - This will install the Hardhat-foundry plugin and the Hardhat toolbox plugin which is a combination of all the
Noted. I love attention to detail. Ty.

2023-11-24 19:19 UTC, Genesis3800 commented on src/config/hardhat.md
> +4. `npm i --save-dev @nomicfoundation/hardhat-foundry @nomicfoundation/hardhat-toolbox` - This will install the Hardhat-foundry plugin and the Hardhat toolbox plugin which is a combination of all the
replaced all instances of `Hardhat-foundry` with `hardhat-foundry`

2023-11-24 19:20 UTC, Genesis3800 commented on src/config/hardhat.md
> +};
Done

2023-11-24 19:20 UTC, Genesis3800 commented on src/config/hardhat.md
> +const { expect } = require("chai");
Done.

2023-11-24 19:27 UTC, Genesis3800 commented
@Evalir Addressed all of @fvictorio 's comments. Besides the repo ownership thing, everything's done. Pls help me merge 🥹🥹🥹

2023-11-28 17:04 UTC, Genesis3800 commented on src/config/hardhat.md
> +[Enjoy!](https://github.com/Genesis3800/HardhatInFoundry)
@Evalir friendly reminder on this.

2023-11-28 21:17 UTC, Evalir requested changes
looks great1! just a small nit. After that, we can transfer the repo and merge

2023-11-28 21:17 UTC, Evalir commented on src/config/hardhat.md
> +[Enjoy!](https://github.com/Genesis3800/HardhatInFoundry)
Yep, let's transfer to the foundry org 🙏 feel free to transfer it to me first

2023-11-28 21:17 UTC, Evalir commented on src/config/hardhat.md
> +2. `npm i --save-dev hardhat` - Install Hardhat into the same directory.
A bit of a nit but this installs hardhat as a dev dep, it doesn't quite install hardhat on the directory.

2023-11-29 17:12 UTC, Genesis3800 commented on src/config/hardhat.md
> +[Enjoy!](https://github.com/Genesis3800/HardhatInFoundry)
Hey @Evalir I am changing the Github link to `https://github.com/foundry-rs/HardhatInFoundry`

This link should start working the moment you transfer the repo to the Foundry org, provided you don't change the name of course.

2023-11-29 17:13 UTC, Genesis3800 commented on src/config/hardhat.md
> +2. `npm i --save-dev hardhat` - Install Hardhat into the same directory.
Good catch, resolving this.

2023-11-30 16:32 UTC, fvictorio commented
LGTM :+1:

2023-12-01 01:44 UTC, mds1 commented
Thanks for the review @fvictorio!

> The example repository has a couple of directories that shouldn't be committed: `artifacts` and `cache_hardhat`.

@Genesis3800 Can you add these to the gitignore in that repo also? And @fvictorio are there any other hardhat specific paths worth adding to that gitignore?

2023-12-01 10:01 UTC, Genesis3800 commented
> Thanks for the review @fvictorio!
> 
> > The example repository has a couple of directories that shouldn't be committed: `artifacts` and `cache_hardhat`.
> 
> @Genesis3800 Can you add these to the gitignore in that repo also? And @fvictorio are there any other hardhat specific paths worth adding to that gitignore?

Done @mds1 , The rest is up to @Evalir

2023-12-01 16:55 UTC, Evalir commented
now we're set! merging

2023-12-01 16:56 UTC, Evalir approved these changes

2023-12-01 16:56 UTC, merged

2023-12-01 19:59 UTC, Genesis3800 commented
Lots of love to everyone who helped me get this done. I'm giving you all some love cause that's all I have to give lol.