docs(formatter): update with new options
foundry-rs/book pull request #1116
Opened 2024-02-13 08:39 UTC by sambacha

add new options  
amend with additional examples

2024-02-13 13:41 UTC, onbjerg requested changes
lgtm otherwise

2024-02-13 13:41 UTC, onbjerg commented on src/reference/config/formatter.md
> +-   `"preserve"` - Keep the existing single/multi line formatting of statement blocks.
nit: remove the additional newline between these

2024-02-13 13:41 UTC, onbjerg commented on src/reference/config/formatter.md
> +-   `"all"` - If function parameters or attributes are multiline, multiline everything
nit: remove the additional newline between these

2024-02-13 13:41 UTC, onbjerg commented on src/reference/config/formatter.md
> +-   Then sorts the import statements within each group alphabetically.
nit: remove the additional newline between these

2024-03-02 08:06 UTC, mattsse approved these changes

2024-03-02 08:19 UTC, merged

2024-03-28 21:30 UTC, blowme8888 commented
I