added soldeer docs
foundry-rs/book pull request #1205
Opened 2024-05-25 14:12 UTC by mario-eth

Added soldeer documentation to the book, i tried to mimic the `dependencies` section.

2024-05-26 17:56 UTC, onbjerg requested changes
you need to add it to summary.md as well otherwise it wont be rendered in the book:)

2024-05-27 05:15 UTC, mario-eth commented
> you need to add it to summary.md as well otherwise it wont be rendered in the book:)

Ah correct, thanks, corrected!

2024-05-30 12:49 UTC, onbjerg requested changes

2024-05-30 12:49 UTC, onbjerg commented on src/projects/soldeer.md
> +- We encourage everyone to use version pinning when importing them into the contracts, this will help with securying your code by knowing exactly what version of a dependency you are using. Furthermo
can you use the format that other pages use here, e.g.

```md
> **Warning** (maybe an emoji)
> - Once a ..
> ..
```

2024-06-01 13:16 UTC, onbjerg approved these changes

2024-06-01 13:16 UTC, onbjerg commented on src/projects/soldeer.md
> +- We encourage everyone to use version pinning when importing them into the contracts, this will help with securying your code by knowing exactly what version of a dependency you are using. Furthermo
```suggestion
> **Warning** ⚠️
> - Once a project is created, it cannot be deleted.
> - Once a version is pushed, it cannot be deleted.
> - You cannot push the same version twice.
> - The project name in the command that you run in the terminal must match the project name that you created on the Soldeer website.
> - We encourage everyone to use version pinning when importing them into the contracts, this will help with securying your code by knowing exactly what version of a dependency you are using. Furthermore, it will help security researchers in their work.
```

2024-06-01 13:16 UTC, merged