Forge Std docs
foundry-rs/book pull request #207
Opened 2022-04-15 21:55 UTC by ZeroEkkusu

2022-04-16 00:22 UTC, onbjerg commented
I think we should just teach using forge-std from the get-go. Do you have a preference @gakonst?

2022-04-16 01:53 UTC, gakonst commented
Yeah let's encourage forge std everywhere!

2022-04-16 15:00 UTC, ZeroEkkusu commented
Any plans for making Forge Std the standard library and shipping it instead of Dappsys Test, with a new template?

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.10;

import "forge-std/Test.sol";

contract ContractTest is Test {
    function setUp() public {}

    function testExample() public {
        assertTrue(true);
    }
}
```

2022-04-16 18:13 UTC, gakonst commented
Already done in the template! https://github.com/foundry-rs/forge-template/blob/master/test/Contract.t.sol

2022-04-16 19:51 UTC, ZeroEkkusu commented
That's great - I'll write the docs accordingly.

Also, not be the best place to ask this, but, would @transmissions11 want to add `bound` to Forge Std, as it complements `vm.assume` well? I think it would come in handy with Forge Std as the standard library.

2022-04-16 21:13 UTC, transmissions11 commented
yup we've been thinking about that

2022-04-18 16:30 UTC, gakonst commented
I think you checked the entirety of forge-std instead of adding it as a submodule btw

2022-04-18 18:50 UTC, onbjerg commented
> I think you checked the entirety of forge-std instead of adding it as a submodule btw

I did that, but it's on purpose. We could do a submodule as well but I chose not to for DSTest at least. It was primarily to not have people do `git submodule update init --recursive` etc to contribute

2022-04-18 21:41 UTC, gakonst commented
Submodule better IMO, we can just add it to the readme as a step, lets us keep the repo up to date and separated

2022-04-19 22:26 UTC, ZeroEkkusu commented
@onbjerg, it's ready.

I will review it once again tomorrow - unless you review it before then.

Defiantly ping me if you need help with something.

Below are some notes on what has changed or been added to the book.

- **New chapters:**
  - Forge Standard Library
  - Forge Standard Library Reference
- **Major changes:**
  - Writing Tests
  - Cheatcodes
- **Minor changes:**
  - Dappsys Test Reference
  - Cheatcodes Reference (also added `Related` section to some cheatcodes)
 - **Lots of tiny changes in misc sections**
 
 There's also more to do after we add this to the book (will open an issue):

- update the NFT tutorial
- add examples for std-errors
- revise when forge-std `v0.2.0` is out (ds-test and everything)
- add more comprehensive docs for std-storage

2022-04-20 00:02 UTC, gakonst commented
@ZeroEkkusu this is great! can you please replace the checked in forge-std with a submodule?

2022-04-20 14:07 UTC, ZeroEkkusu reviewed
Todo:

- [ ] fix misc
- [ ] run the scripts
- [ ] resolve conflicts
- [ ] change forge std to a submodule

2022-04-20 15:19 UTC, ZeroEkkusu commented
@onbjerg, would you fix forge-std

Let's run the scripts afterward
(also seems like we must to add `src` to all the projects or it will complain)

2022-04-20 16:31 UTC, onbjerg commented
wdym fix?

2022-04-20 16:37 UTC, ZeroEkkusu commented
oh, what Georgios asked - to use a submodule instead

2022-04-21 19:45 UTC, ZeroEkkusu commented
@onbjerg fyi #223 is already fixed, we just need to switch to using submodules as discussed above.

2022-04-21 20:41 UTC, onbjerg requested changes
I moved to submodules now (remember to run `git submodule update --init --recursive` after pulling the changes). I also went through the entire PR:

Generally, looks really good! Thank you for your hard work :smile: :rocket: 

I have a lot of small nits, mostly around naming (hevm, std-*, DappSys), but I also have some questions, notably for some of the errors in Std Errors and for most of the Std Storage docs.

Let me know if this is overwhelming or if you disagree with some of them: these are not necessarily blocking. If you agree with the changes but still find it overwhelming, let me know, and I will help you address the things :blush:

2022-04-21 20:41 UTC, onbjerg commented on src/README.md
> +- [Dappsys Test Reference](./reference/ds-test.md)
I think Dappsys Test is too long, maybe we should just stick to DSTest?

2022-04-21 20:41 UTC, onbjerg commented on src/SUMMARY.md
> +    - [Std-cheats](./reference/forge-std/std-cheats.md)
Std-cheats looks weird and we don't need to be 100% in line with what the library is called here (or in the heading of the file) as long as we explain how to import them.

```suggestion
    - [Std Cheats](./reference/forge-std/std-cheats.md)
```

2022-04-21 20:41 UTC, onbjerg commented on src/SUMMARY.md
> +    - [Std-errors](./reference/forge-std/std-errors.md)
Same as above

```suggestion
    - [Std Errors](./reference/forge-std/std-errors.md)
```

2022-04-21 20:41 UTC, onbjerg commented on src/SUMMARY.md
> +    - [Std-storage](./reference/forge-std/std-storage.md)
Same as above

```suggestion
    - [Std Storage](./reference/forge-std/std-storage.md)
```

2022-04-21 20:41 UTC, onbjerg commented on src/SUMMARY.md
> +  - [Dappsys Test Reference](./reference/ds-test.md)
Same as in the cover of the book

```suggestion
  - [DSTest Reference](./reference/ds-test.md)
```

2022-04-21 20:41 UTC, onbjerg commented on src/cheatcodes/README.md
> +To enable a cheatcode you call designated functions on the cheatcode address: `0x7109709ECfa91a80626fF3989D68f67F5b1DD12D`, often refered to as 'Hevm'.
The "Hevm" name is a leftover from DappTools and we don't really refer to it as such anywhere in Forge

```suggestion
To enable a cheatcode you call designated functions on the cheatcode address: `0x7109709ECfa91a80626fF3989D68f67F5b1DD12D`.
```

2022-04-21 20:41 UTC, onbjerg commented on src/cheatcodes/README.md
> +You can access Hevm easily via `vm` available in Forge Standard Library's [`Test`](../reference/forge-std/#forge-stds-test).
```suggestion
You can access cheatcodes easily via `vm` available in Forge Standard Library's [`Test`](../reference/forge-std/#forge-stds-test) contract.
```

2022-04-21 20:41 UTC, onbjerg commented on src/cheatcodes/deal.md
> +### Related
I think we should name these sections "See also" like in the command reference

2022-04-21 20:41 UTC, onbjerg commented on src/cheatcodes/etch.md
> +### Related
Same as above

2022-04-21 20:41 UTC, onbjerg commented on src/cheatcodes/expect-revert.md
> +### Related
Same as above

2022-04-21 20:41 UTC, onbjerg commented on src/cheatcodes/expect-revert.md
> +- [Std-errors](../reference/forge-std/std-errors.md)
```suggestion
- [Std Errors](../reference/forge-std/std-errors.md)
```

2022-04-21 20:41 UTC, onbjerg commented on src/cheatcodes/get-code.md
> +### Related
Same as above

2022-04-21 20:41 UTC, onbjerg commented on src/cheatcodes/get-code.md
>  [forge-std]: https://github.com/foundry-rs/forge-std
We should change this link to link to the top-level of the Forge Std reference

2022-04-21 20:41 UTC, onbjerg commented on src/cheatcodes/load.md
> +### Related
Same as above, "See also"

2022-04-21 20:41 UTC, onbjerg commented on src/cheatcodes/load.md
> +- [Std-storage](../reference/forge-std/std-storage.md)
```suggestion
- [Std Storage](../reference/forge-std/std-storage.md)
```

2022-04-21 20:41 UTC, onbjerg commented on src/cheatcodes/prank.md
> +### Related
Same as above, "See also"

2022-04-21 20:41 UTC, onbjerg commented on src/cheatcodes/record.md
> +### Related
Same as above, "See also"

2022-04-21 20:41 UTC, onbjerg commented on src/cheatcodes/record.md
> +- [Std-storage](../reference/forge-std/std-storage.md)
```suggestion
- [Std Storage](../reference/forge-std/std-storage.md)
```

2022-04-21 20:41 UTC, onbjerg commented on src/cheatcodes/start-prank.md
> +### Related
Same as above, "See also"

2022-04-21 20:41 UTC, onbjerg commented on src/cheatcodes/store.md
> +### Related
Same as above, "See also"

2022-04-21 20:41 UTC, onbjerg commented on src/cheatcodes/store.md
> +- [Std-storage](../reference/forge-std/std-storage.md)
```suggestion
- [Std Storage](../reference/forge-std/std-storage.md)
```

2022-04-21 20:41 UTC, onbjerg commented on src/cheatcodes/warp.md
> +### Related
Same as above, "See also"

2022-04-21 20:41 UTC, onbjerg commented on src/forge/cheatcodes.md
> +Cheatcodes allow you to change the block number, your identity, and more. They are invoked by calling specific functions on a specially designated address: `0x7109709ECfa91a80626fF3989D68f67F5b1DD12D
Leftover from DappTools

```suggestion
Cheatcodes allow you to change the block number, your identity, and more. They are invoked by calling specific functions on a specially designated address: `0x7109709ECfa91a80626fF3989D68f67F5b1DD12D`.
```

2022-04-21 20:41 UTC, onbjerg commented on src/forge/cheatcodes.md
> +You can access Hevm easily via the `vm` instance available in Forge Standard Library's `Test` (Forge Standard Library is explained in greater detail in the following [section](./forge-std.md)).
```suggestion
You can access cheatcodes easily via the `vm` instance available in Forge Standard Library's `Test` contract. Forge Standard Library is explained in greater detail in the following [section](./forge-std.md).
```

2022-04-21 20:41 UTC, onbjerg commented on src/forge/forge-std.md
> +- `Test.sol`: Std-libraries, Dappsys Test, Hevm instance, and Hardhat console
```suggestion
- `Test.sol`: A superset of DSTest containing standard libraries, a cheatcodes instance (`vm`), and Hardhat console
```

2022-04-21 20:41 UTC, onbjerg commented on src/forge/forge-std.md
> +**Note:** `console2.sol` decodes logs with `int256` and `uint256` values correctly, but is not compatible with Hardhat.
Also maybe we should make this one of those light-bulby things?

```suggestion
**Note:** `console2.sol` contains patches to `console.sol` that allows Forge to decode traces for calls to the console, but it is not compatible with Hardhat.
```

2022-04-21 20:41 UTC, onbjerg commented on src/forge/forge-std.md
> +### Std-libraries
```suggestion
### Standard Libraries
```

2022-04-21 20:41 UTC, onbjerg commented on src/forge/forge-std.md
> +#### Std-cheats
```suggestion
#### Std Cheats
```

2022-04-21 20:41 UTC, onbjerg commented on src/forge/forge-std.md
> +Std-cheats are wrappers around the Forge cheatcodes, to make them safer to use and improve the UX.
```suggestion
Std Cheats are wrappers around the Forge cheatcodes, that make them safer to use and improve the UX.
```

2022-04-21 20:41 UTC, onbjerg commented on src/forge/forge-std.md
> +You can access std-cheats by simply calling them inside your test contract, as you would any other internal function:
```suggestion
You can access Std Cheats by simply calling them inside your test contract, as you would any other internal function:
```

2022-04-21 20:41 UTC, onbjerg commented on src/forge/forge-std.md
> +#### Std-errors
```suggestion
#### Std Errors
```

2022-04-21 20:41 UTC, onbjerg commented on src/forge/forge-std.md
> +Std-errors are common Solidity errors and reverts.
```suggestion
Std Errors provide wrappers around common internal Solidity errors and reverts.
```

2022-04-21 20:41 UTC, onbjerg commented on src/forge/forge-std.md
> +Std-errors are most useful in combination with the [`expectRevert`](../cheatcodes/expect-revert.md#expectrevert) cheatcode, as you do not need to remember the panic codes. Note that you have to acces
```suggestion
Std Errors are most useful in combination with the [`expectRevert`](../cheatcodes/expect-revert.md) cheatcode, as you do not need to remember the internal Solidity panic codes yourself. Note that you have to access them through `stdError`, as this is a library.
```

2022-04-21 20:41 UTC, onbjerg commented on src/forge/forge-std.md
> +#### Std-storage
```suggestion
#### Std Storage
```

2022-04-21 20:41 UTC, onbjerg commented on src/forge/forge-std.md
> +Std-storage makes manipulating contract storage easy. It can always find and write to the storage slot(s) associated with a particular variable.
There may be some issues with packed slots last I saw

```suggestion
Std Storage makes manipulating contract storage easy. It can find and write to the storage slot(s) associated with a particular variable.
```

2022-04-21 20:41 UTC, onbjerg commented on src/forge/writing-tests.md
> +Using the [Forge Standard Library](https://github.com/foundry-rs/forge-std) is the preferred way of writing tests with Foundry.
```suggestion
Let's go over the most common way of writing tests, using the [Forge Standard Library](https://github.com/foundry-rs/forge-std)'s `Test` contract, which is the preferred way of writing tests with Forge.
```

2022-04-21 20:41 UTC, onbjerg commented on src/forge/writing-tests.md
> +In this section, we'll go over the basics using the functions from the [Dappsys Test](https://github.com/dapphub/ds-test) library, which is included in the Forge Standard Library. You will learn how
```suggestion
In this section, we'll go over the basics using the functions from the Forge Std's `Test` contract, which is itself a superset of [DSTest](https://github.com/dapphub/ds-test). You will learn how to use more advanced stuff from the Forge Standard Library [soon](./forge-std.md). 
```

2022-04-21 20:41 UTC, onbjerg commented on src/forge/writing-tests.md
> +Dappsys Test provides basic logging and assertion functionality. To get access to the functions, import `forge-std/Test.sol` and inherit from `Test` in your test contract:
```suggestion
DSTest provides basic logging and assertion functionality. To get access to the functions, import `forge-std/Test.sol` and inherit from `Test` in your test contract:
```

2022-04-21 20:41 UTC, onbjerg commented on src/forge/writing-tests.md
> +    Now, instead of using `testFail`, you know exactly what reverted:
I think this should work (double space after a line adds a newline)

```suggestion
    A good practice is to use something like `testCannot` in combination with the [`expectRevert`](../cheatcodes/expect-revert.md) cheatcode (cheatcodes are explained in greater detail in the following [section](./cheatcodes.md)).  

    Now, instead of using `testFail`, you know exactly what reverted:
```

2022-04-21 20:41 UTC, onbjerg commented on src/projects/creating-a-new-project.md
> +The default template comes with one dependency installed: Dappsys Test. This is the preferred assertion library used for Foundry projects. Additionally, the template also comes with an empty starter
```suggestion
The default template comes with one dependency installed: DSTest. This is the preferred assertion library used for Foundry projects. Additionally, the template also comes with an empty starter contract and a simple test.
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/ds-test.md
> +## Dappsys Test Reference
```suggestion
## DSTest Reference
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/ds-test.md
> +Dappsys Test provides basic logging and assertion functionality. It is included in the Forge Standard Library.
```suggestion
Dappsys Test (DSTest for short) provides basic logging and assertion functionality. It is included in the Forge Standard Library.
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/README.md
> +    **Note:** `console2.sol` decodes logs with `int256` and `uint256` values correctly, but is not compatible with Hardhat.
```suggestion
    **Note:** `console2.sol` contains patches to `console.sol` that allows Forge to decode traces for calls to the console, but it is not compatible with Hardhat.
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/README.md
> +`Test` in `Test.sol` provides all the essential functionality you need to get started writing tests.
```suggestion
The `Test` contract in `Test.sol` provides all the essential functionality you need to get started writing tests.
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/README.md
> +  - [Std-storage](./std-storage.md): Contract storage manipulation helpers.
```suggestion
- Std Libraries
  - [Std Cheats](./std-cheats.md): Wrappers around Forge cheatcodes for improved safety and UX.
  - [Std Errors](./std-errors.md): Common Solidity errors and reverts.
  - [Std Storage](./std-storage.md): Contract storage manipulation helpers.
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/README.md
> +- A Hevm instance `vm`, via which you invoke Forge cheatcodes (see [Cheatcodes Reference](../../cheatcodes/))
```suggestion
- A cheatcodes instance `vm`, from which you invoke Forge cheatcodes (see [Cheatcodes Reference](../../cheatcodes/))
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/arithmeticError.md
> +The error when an arithmetic operation fails, e.g. underflow, overflow.
```suggestion
The internal Solidity error when an arithmetic operation fails, e.g. underflow and overflow.
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/assertionError.md
> +The error when an assertion fails.
```suggestion
The internal Solidity error when an `assert` fails.
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/deal.md
> +The same as [`deal`](../../cheatcodes/deal.md) cheatcode, but works for any ERC-20 token as well.
Some non-standard tokens may not work last I checked

```suggestion
A wrapper around the [`deal`](../../cheatcodes/deal.md) cheatcode that also works for most ERC-20 tokens.
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/divisionError.md
> +The error when a division fails, e.g. division by zero.
```suggestion
The internal Solidity error when a division fails, e.g. division by zero.
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/encodeStorageError.md
> +The error when trying to access data in storage that is corrupted. Cannot happen unless assembly is used.
Is this an internal Solidity error? If so, same as above

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/enumConversionError.md
> +The error when a number does not exist in an `enum`.
More precise

```suggestion
The internal Solidity error when trying to convert a number to a variant of an enum, if the number is larger than the number of variants in the enum.
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/hoax.md
> +If the balance is not specified, it will be set to 2^128 ETH.
Surely this is wei and not eth?

```suggestion
If the balance is not specified, it will be set to `2^128` wei.
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/indexOOBError.md
> +The error when trying to access an element of an array that is out of bounds.
```suggestion
The internal Solidity error when trying to access an element of an array that is out of bounds.
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/memOverflowError.md
> +The error when trying to allocate size of a dynamic memory array greater than 2^64-1.
Is this the number of items or the size of the array, i.e. if I allocate a dynamic memory array with 2 items and both items have a size of `2^32` bytes, would this panic?

```suggestion
The internal Solidity error when trying to allocate a dynamic memory array with more than `2^64-1` items.
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/popError.md
> +The error when there is no element to remove from the end of an array.
```suggestion
The internal Solidity error when trying to pop an element off of an empty array.
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/startHoax.md
> +If the balance is not specified, it will be set to 2^128 ETH.
Again, surely this is wei?

```suggestion
If the balance is not specified, it will be set to `2^128` wei.
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/std-cheats.md
> +## Std-cheats
```suggestion
## Std Cheats
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/std-errors.md
> +## Std-errors
```suggestion
## Std Errors
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/std-storage.md
> +## Std-storage
```suggestion
## Std Storage
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/std-storage.md
> +To use std-storage, add the following line to your test contract:
```suggestion
To use Std Storage, add the following line to your test contract:
```

Additionally, we should give a short explainer of what Std Storage is: it's a library to manipulate the storage of contracts.

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/std-storage.md
> +Then, access std-storage via the `stdstore` instance.
```suggestion
Then, access Std Storage via the `stdstore` instance.
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/std-storage.md
> +- `with_key`: Set key, if variable is of type `mapping`.
```suggestion
- `with_key`: Set key, if the slot you are looking for is a mapping.
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/std-storage.md
> +- `depth`: Set depth, if variable is of type `struct`.
I assume `depth` here is actually the number of the member variable you are looking up in the struct? E.g. if I have a struct:

```solidity
struct Abc {
  uint256 x; // depth = 0
  uint256 y; // depth = 1
}
```

If so, we should try to convey that in a simple manner, e.g. "Set the index of the struct member if the slot you are looking for is a struct" or something.

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/std-storage.md
> +- `sig`: Set function signature.
```suggestion
- `sig`: Set function signature to call.
```

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/std-storage.md
> +### Functions
Do you need to call all of these functions, or can you chain them as you wish? I.e. is `target(someContract).sig(someFunction.selector).find()` valid? What if I don't call `target` but instead `sig(someSig).find()`? 

If not, we should probably split these into:

- Query functions (target, sig, slot etc.): Limits your search for a storage slot
- Terminator functions (`checked_write`, `find`): Performs the query (either a write or a read)

We should additionally explain if any of these are required

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/std-storage.md
> +- `checked_write`: Set data to be written.
```suggestion
- `checked_write`: Set data to be written to the storage slot.
```

Additionally, what happens if the query matches multiple slots? What if it matches no slots?

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/std-storage.md
> +- `find`: Return slot number.
Same question as above

2022-04-21 20:41 UTC, onbjerg commented on src/reference/forge-std/zeroVarError.md
> +The error when trying to call a function via an in-function function pointer that has not been initialized.
```suggestion
The internal Solidity error when trying to call a function via a function pointer that has not been initialized.
```

2022-04-21 20:58 UTC, ZeroEkkusu commented
Good suggestions; I'll fix those tomorrow morning!

2022-04-22 11:49 UTC, ZeroEkkusu commented on src/forge/forge-std.md
> +**Note:** `console2.sol` decodes logs with `int256` and `uint256` values correctly, but is not compatible with Hardhat.
I'd rather not use callouts here (looks crammed).

2022-04-22 17:04 UTC, ZeroEkkusu commented on src/reference/forge-std/std-storage.md
> +- `with_key`: Set key, if variable is of type `mapping`.
Maybe we should come up with a better explanation for this one and the one below

2022-04-22 19:35 UTC, ZeroEkkusu commented on src/reference/forge-std/memOverflowError.md
> +The error when trying to allocate size of a dynamic memory array greater than 2^64-1.
Could you help with this? I'm sometimes getting a revert without data for arbitrary values.

Also, [Solidity Blog post](https://blog.soliditylang.org/2020/04/06/memory-creation-overflow-bug/#technical-details)

2022-04-22 19:50 UTC, ZeroEkkusu commented on src/reference/forge-std/std-storage.md
> +- `checked_write`: Set data to be written.
Help. I need to familiarize myself with Std Storage inner workings more ><

Also, we'll probably need to add a Troubleshooting section to Std Storage (later)

2022-04-22 20:21 UTC, ZeroEkkusu commented
I need to learn about Std Storage more and expand the section. Generally speaking, I think it's best to ship and improve later, rather than wait.

Left comments for things I was unsure about.

2022-04-23 13:12 UTC, onbjerg approved these changes
Ok, agree. Let's merge and go over Std Storage separately. Looks good! Amazing work :smile:

2022-04-23 13:12 UTC, merged

2022-04-23 14:37 UTC, ZeroEkkusu commented
Thank you for helping me.

Also thanks @gakonst for your input.