WIP: Differential Testing and FFI
foundry-rs/book pull request #225
Opened 2022-04-22 02:37 UTC by dmfxyz

Opening for visibility. About halfway through, still have 2 more examples to add. Also would be great to include Frankie's stuff, but don't want to do that without permission / collaboration.

Addresses #182

2022-04-25 04:08 UTC, onbjerg commented on src/forge/differential-ffi-testing.md
> +```
Tests are failing here, just add ```ignore

2022-04-25 04:54 UTC, onbjerg requested changes
Amazing! Very simple to understand, at least in my opinion - I had not come across differential testing before, but the concept seems simple and I understood what was conveyed in the text

I've left some very small nits, most of them are just some casing/links and 1 typo

2022-04-25 04:54 UTC, onbjerg commented on src/forge/differential-ffi-testing.md
> +[Differential testing](https://en.wikipedia.org/wiki/Differential_testing) cross references multiple implementations of the same function by comparing each one's output. Imagine we have a function sp
This is mostly a matter of habit for me, I'm not sure if the `EQ` notation is something formal - if it is, then feel free to skip

```suggestion
[Differential testing](https://en.wikipedia.org/wiki/Differential_testing) cross references multiple implementations of the same function by comparing each one's output. Imagine we have a function specification `F(X)`, and two implementations of that specification: `f1(X)` and `f2(X)`. We expect that `f1(x) == f2(x)` for all x that exist in an appropriate input space If `f1(x) != f2(x)`, then we know that at least one function is incorrectly implementing `F(X)`. This process of testing for equality and identifying discrepancies is the core of differential testing.
```

2022-04-25 04:54 UTC, onbjerg commented on src/forge/differential-ffi-testing.md
> +`ffi` allows you to execute an arbitrary shell command and capture the output. Here's a mock example:
Just a little link to the FFI cheatcode

```suggestion
[`ffi`](../cheatcodes/ffi.md) allows you to execute an arbitrary shell command and capture the output. Here's a mock example:
```

2022-04-25 04:54 UTC, onbjerg commented on src/forge/differential-ffi-testing.md
> +[Merkle Trees](https://en.wikipedia.org/wiki/Merkle_tree) are a cryptographic commitmentment scheme frequently used in blockchain applications. Their popularity means that there are a number of diffe
One typo + minor nits

```suggestion
[Merkle Trees](https://en.wikipedia.org/wiki/Merkle_tree) are a cryptographic commitmentment scheme frequently used in blockchain applications. Their popularity means that there are a number of different implementations of Merkle Tree generators, provers, and verifiers. Often, Merkle roots and proofs are generated using a language like JavaScript or Python, and proofs are verified on-chain in Solidity.
```

2022-04-25 04:54 UTC, onbjerg commented on src/forge/differential-ffi-testing.md
> +[Murky](https://github.com/dmfxyz/murky) is a complete implementation of Merkle roots, proofs, and verification in solidity. Its test suite includes differential tests against OpenZeppelin's Merkle p
```suggestion
[Murky](https://github.com/dmfxyz/murky) is a complete implementation of Merkle roots, proofs, and verification in Solidity. Its test suite includes differential tests against OpenZeppelin's Merkle proof verification implementation, as well as root generation tests against a reference JavaScript implementation. These tests are powered by Foundry's fuzzing and `ffi` capabilities.
```

2022-04-25 04:54 UTC, onbjerg commented on src/forge/differential-ffi-testing.md
> +Using the `ffi` cheatcode, Murky tests its own Merkle root implementation against a TypeScript implementation using data provided by forge's fuzzer:
```suggestion
Using the `ffi` cheatcode, Murky tests its own Merkle root implementation against a TypeScript implementation using data provided by Forge's fuzzer:
```

2022-04-25 04:54 UTC, onbjerg commented on src/forge/differential-ffi-testing.md
> +forge runs `npm --prefix differential_testing/scripts/ --silent run generate-root-cli {numLeaves} {hexEncodedLeaves}`. This calculates the Merkle root for the input data using the reference JavaScrip
```suggestion
Forge runs `npm --prefix differential_testing/scripts/ --silent run generate-root-cli {numLeaves} {hexEncodedLeaves}`. This calculates the Merkle root for the input data using the reference JavaScript implementation. The script prints the root to stdout, and that printout is captured as `bytes` in the return value of `vm.ffi()`.
```

2022-04-25 04:54 UTC, onbjerg commented on src/forge/differential-ffi-testing.md
> +The test then calculates the root using the solidity implementation.
```suggestion
The test then calculates the root using the Solidity implementation.
```

2022-04-25 04:54 UTC, onbjerg commented on src/forge/differential-ffi-testing.md
> +You may want to use differential testing against another solidity implementation. In that case, `ffi` is not needed. In this example, the reference implementation is imported directly into the test.
```suggestion
You may want to use differential testing against another Solidity implementation. In that case, `ffi` is not needed. In this example, the reference implementation is imported directly into the test.
```

2022-04-25 04:54 UTC, onbjerg commented on src/forge/differential-ffi-testing.md
> +FFI is also useful for injecting reproducible, standardized data into the testing environment. In the Murky library, this is used as a benchmark for gas snapshotting (see: [forge snapshot](./gas-snap
```suggestion
FFI is also useful for injecting reproducible, standardized data into the testing environment. In the Murky library, this is used as a benchmark for gas snapshotting (see [forge snapshot](./gas-snapshots.md)).
```

2022-04-25 04:54 UTC, onbjerg commented on src/forge/differential-ffi-testing.md
> +`src/test/standard_data/StandardInput.txt` is a text file that contains an encoded bytes32[100] array. It's generated outside of the test and can be used in any language's web3 sdk. It looks somethin
```suggestion
`src/test/standard_data/StandardInput.txt` is a text file that contains an encoded `bytes32[100]` array. It is generated outside of the test and can be used in any language's Web3 SDK. It looks something like:
```

2022-04-25 06:20 UTC, FrankieIsLost commented
I apologize for the slow response here, this look great! Really thorough write-up and examples, and lines up with how I've been using differential testing. 

One minor suggestion might be to clarify the distinction between differential testing and differential fuzzing. For example, you can write differential tests with FFI without relying on the fuzzer, which is helpful when you want to manually check certain edge-cases. 

Regarding GDA testing, feel free to link. 

Thanks for taking point on this!

2022-04-25 19:29 UTC, dmfxyz commented on src/forge/differential-ffi-testing.md
> +[Differential testing](https://en.wikipedia.org/wiki/Differential_testing) cross references multiple implementations of the same function by comparing each one's output. Imagine we have a function sp
Ack. I used `EQ` because it's not always a strict equivalence function the way many programmers may think when they see `==`, but I replaced it with your suggestion and just added a note as I do think it's more readable.

2022-04-25 19:31 UTC, dmfxyz commented
Thanks for the feedback! @onbjerg I addressed your first round of comments. Agree that I should add a non-fuzzed differential use-case, and I already have an example of that in the Murky repo. I'll write that up tonight and also link to the GDA repo, and then I think we should be ready for another review and merge.

2022-04-26 04:07 UTC, dmfxyz commented
OK! I think we're ready for a final review. cc @gakonst as well if you have time to give it a quick read.

2022-04-26 07:45 UTC, gakonst approved these changes

2022-04-26 07:45 UTC, gakonst commented on src/forge/differential-ffi-testing.md
> +* Confirming compatability with third party tools and dependencies
```suggestion
* Confirming compatibility with third party tools and dependencies
```

2022-04-26 13:20 UTC, onbjerg approved these changes
last nit and then we merge!!

2022-04-26 13:20 UTC, onbjerg commented on src/forge/differential-ffi-testing.md
> +* Reference [Python implementation](https://github.com/FrankieIsLost/gradual-dutch-auction/blob/master/analysis/compute_price.py)
Spacing is off in the rendered doc otherwise

```suggestion
* Differential tests for [Discrete GDAs](https://github.com/FrankieIsLost/gradual-dutch-auction/blob/master/src/test/DiscreteGDA.t.sol#L78)
* Differential tests for [Continuous GDAs](https://github.com/FrankieIsLost/gradual-dutch-auction/blob/master/src/test/ContinuousGDA.t.sol#L89)
* Reference [Python implementation](https://github.com/FrankieIsLost/gradual-dutch-auction/blob/master/analysis/compute_price.py)
```

2022-04-26 14:33 UTC, mds1 commented
Wow this is really great, nice and detailed!! Awesome job @dmfxyz

2022-04-26 14:34 UTC, merged

2022-04-26 17:33 UTC, cruzdanilo commented
@dmfxyz  where does `(bytes memory).toHexString()` come from?

2022-04-26 17:47 UTC, dmfxyz commented
> @dmfxyz where does `(bytes memory).toHexString()` come from?

@cruzdanilo this is from library implementation I wrote in for the Murky library. I called it [`Strings2]`(https://github.com/dmfxyz/murky/blob/main/differential_testing/test/utils/Strings2.sol) for now. Might move it out of that repo to somewhere more shared, but feel free to copy paste as you need for now.