docs: fix `cast call` example command
foundry-rs/book pull request #230
Opened 2022-04-23 22:23 UTC by Galmoli

2022-04-24 15:14 UTC, onbjerg requested changes
You need to update it in this file: https://github.com/foundry-rs/book/blob/master/scripts/generate-output-cast

The file you edited is auto-generated

2022-04-25 08:45 UTC, Galmoli commented
I ran `generate-output-cast` and it generated the output correctly, so https://github.com/foundry-rs/book/blob/master/src/output/cast/cast-call has quotation marks.

2022-04-25 16:32 UTC, gakonst approved these changes

2022-04-25 16:32 UTC, merged

2022-04-26 13:14 UTC, onbjerg commented
@all-contributors add @Galmoli for maintenance