feat(installation.md): feat update to latest command
foundry-rs/book pull request #275
Opened 2022-05-04 14:29 UTC by wiasliaw

1. According to https://github.com/foundry-rs/foundry/pull/1037, current installation command will get error below.

```
error: multiple packages with binaries found: anvil, foundry-cli. When installing a git repository, cargo will always search the entire repo for any Cargo.toml. Please specify which to install.
```

2. provide update command to get the latest version of Foundry.

2022-05-04 17:57 UTC, onbjerg requested changes
Any way we can get it to install Anvil as well?

2022-05-04 18:30 UTC, gakonst commented
@mattsse should we pull in the Anvil binary into `foundry-cli` so that all CLI bins are in the same package and avoid this issue?

2022-05-04 18:57 UTC, mattsse commented
> @mattsse should we pull in the Anvil binary into `foundry-cli` so that all CLI bins are in the same package and avoid this issue?

if we do this then testing in `cli` will take get even longer.

I have no better solution yet, need to try something first.
the current setup of the `foundry-cli` is also not ideal, because it's essentially two crates in itself.

2022-05-05 15:01 UTC, onbjerg reviewed
To also install Anvil

2022-05-05 15:01 UTC, onbjerg commented on src/getting-started/installation.md
> +cargo install --git https://github.com/foundry-rs/foundry foundry-cli --bins --locked
```suggestion
cargo install --git https://github.com/foundry-rs/foundry foundry-cli anvil --bins --locked
```

2022-05-05 15:02 UTC, merged