docs: document forge cache
foundry-rs/book pull request #280
Opened 2022-05-05 03:04 UTC by shawnharmsen

issue: https://github.com/foundry-rs/book/issues/270

- Not sure if I should have it under Forge Build Commands
- Will do some more work with the examples / options for forge cache clean

2022-05-05 14:59 UTC, onbjerg requested changes
Thanks for this! Some minor changes :smile:

2022-05-05 14:59 UTC, onbjerg commented on src/SUMMARY.md
> +      - [forge cache clean](./reference/forge/forge-cache-clean.md)
This fits better under Utility since the cache is not related to building, it's related to running (both `forge run` and `forge test`)

2022-05-05 14:59 UTC, onbjerg commented on src/reference/forge/forge-cache-clean.md
> +`forge cache clean` [*options*] [*--*] [*CHAINS*]
For consistency

```suggestion
`forge cache clean` [*options*] [*--*] [*chains..*]
```

2022-05-05 14:59 UTC, onbjerg commented on src/reference/forge/forge-cache-clean.md
> +
Lacks the default options:

```
{{#include common-options.md}}
```

2022-05-05 14:59 UTC, onbjerg commented on src/reference/forge/forge-cache.md
> +&nbsp;&nbsp;&nbsp;&nbsp;Cleans cached data from ~/.foundry.
```suggestion
&nbsp;&nbsp;&nbsp;&nbsp;Cleans cached data from ``~/.foundry``.
```

2022-05-05 14:59 UTC, onbjerg commented on src/reference/forge/forge.md
> +
Remember to move these under utility as well (see first comment)

2022-05-06 01:31 UTC, shawnharmsen commented
Ok I think I got everything

2022-05-06 01:32 UTC, onbjerg approved these changes
thanks :heart:

2022-05-06 01:32 UTC, merged