docs: update verify documentation
foundry-rs/book pull request #324
Opened 2022-05-21 14:54 UTC by shawnharmsen

closes: https://github.com/foundry-rs/book/issues/323

2022-05-21 19:02 UTC, 0xvv approved these changes
Nice catch, looks good

2022-05-21 20:40 UTC, ZeroEkkusu reviewed
Could you also recommend using `--verify` in `deploying.md`?

Something like this:
```text
## Verifying

It is recommended to use the `--verify` flag with `forge create` to automatically verify the contract on Etherscan after a deployment. Note that [`ETHERSCAN_API_KEY`](../reference/config.md#etherscan_api_key) must be set.

If you are verifying an already deployed contract, read on.
```

2022-05-22 05:24 UTC, shawnharmsen commented
this also closes: https://github.com/foundry-rs/book/issues/236

Did not realize there was an issue for this already

--config-path moved from 
`src/reference/forge/core-build-options.md`
to
`src/reference/forge/project-options.md`

There is also an `revert-strings` issue that I will check in a separate pr after this

2022-05-23 04:09 UTC, onbjerg requested changes
Some small nits

2022-05-23 04:09 UTC, onbjerg commented on src/forge/deploying.md
> +If you are verifying an already deployed contract, read on.
We should change the `forge create` section to include `--verify`, and change this section to be "Verifying a pre-existing contract" or something like that

2022-05-23 04:09 UTC, onbjerg commented on src/reference/forge/forge-verify-contract.md
> +&nbsp;&nbsp;&nbsp;&nbsp;Number of attempts for retrying [default: 1].
```suggestion
&nbsp;&nbsp;&nbsp;&nbsp;Number of attempts for retrying. Defaults to 1.
```

for consistency

2022-05-23 04:09 UTC, onbjerg commented on src/reference/forge/forge-verify-contract.md
> +Automatically runs `forge verify-check` until the verification either fails or succeeds.
```suggestion
&nbsp;&nbsp;&nbsp;&nbsp;Wait for verification result after submission.  
&nbsp;&nbsp;&nbsp;&nbsp;Automatically runs `forge verify-check` until the verification either fails or succeeds.
```

for consistency

2022-05-23 04:09 UTC, onbjerg commented on src/reference/forge/project-options.md
> +&nbsp;&nbsp;&nbsp;&nbsp;The project's remappings from the environment. Returns `None` if the env var is not set, otherwise all remappings.
```suggestion

```

this is an implementation specific thing, ideally the user would never see this flag, so we shouldn't document it

2022-05-24 09:22 UTC, shawnharmsen commented
Changes

1. changed the "Verifying" text in `src/forge/deploying.md`
2. forge create page `src/reference/forge/forge-create.md` has the `--verify` flag

Question
1. `src/reference/forge/project-options.md` has `--remappings-env *env*` with no description
- should I remove it entirely or just leave it with no description?

2022-05-27 15:49 UTC, onbjerg commented on src/reference/forge/project-options.md
> +
```suggestion
```

2022-05-27 15:52 UTC, onbjerg approved these changes

2022-05-27 15:52 UTC, merged