docs: add forge script
foundry-rs/book pull request #335
Opened 2022-05-30 04:06 UTC by shawnharmsen

closes: https://github.com/foundry-rs/book/issues/332

2022-05-30 14:51 UTC, onbjerg requested changes
Minor nits, however I think we should include the `forge debug` change in this PR as well. I also think `forge script` should probably be under "Utility Commands" for now, since it sort of replaces `forge run` (which is now just a way to run the debugger)

2022-05-30 14:51 UTC, onbjerg commented on src/reference/forge/forge-script.md
> +&nbsp;&nbsp;&nbsp;&nbsp;Takes precedence over broadcast.
What does it do? If this is the description of the flag in Forge we should fix that upstream as well as this is pretty non-descriptive

2022-05-30 14:51 UTC, onbjerg commented on src/reference/forge/forge-script.md
> +&nbsp;&nbsp;&nbsp;&nbsp;The name of the contract you want to run
```suggestion
&nbsp;&nbsp;&nbsp;&nbsp;The name of the contract you want to run.
```

2022-05-31 05:05 UTC, shawnharmsen commented on src/reference/forge/forge-script.md
> +&nbsp;&nbsp;&nbsp;&nbsp;Takes precedence over broadcast.
It opens it in the debugger.

same results for both commands below

```bash
forge script ./test/Broadcast.t.sol --tc BroadcastTest --sig "deploy()" -vvv --fork-url $GOERLI_RPC_URL --debug
forge debug ./test/Broadcast.t.sol --tc BroadcastTest --sig "deploy()"
```

2022-05-31 06:31 UTC, shawnharmsen commented
Think I got it all

1. Change `forge run` to `forge debug`
2. All `forge script` docs
3. `forge script --debug` help text in foundry pr: https://github.com/foundry-rs/foundry/pull/1782

2022-05-31 20:56 UTC, onbjerg approved these changes

2022-05-31 20:56 UTC, merged