Anvil Documentation
foundry-rs/book pull request #352
Opened 2022-06-01 20:34 UTC by Leutwiler

I wrote four topics for the Anvil documentation:
1) Anvil Flags: covers the possible Anvil flags
2) Mining Modes: talks about the mining modes
3) Supported Transport Layers: defines the supported transport layers (as far as I know and based on a conversation with Matthias, WS is still not supported and requires some code rewriting, so I documented that it will be supported soon)
4) Supported RPC Methods: covers every Anvil's RPC method

This documentation was an incredible experience for me! I could learn many new things about Foundry and other general subjects.

Huge thanks to @mattsse ! He was crucial for this documentation because he helped me a lot with some questions I had! :)

Fix #190

2022-06-02 09:17 UTC, mattsse requested changes
thanks so much for this, this is great!

couple nits otherwise this is a great start

2022-06-02 09:17 UTC, mattsse commented on src/anvil/rpcMethods.md
> +### Standard Methods
can we link to the eth wiki here https://eth.wiki/json-rpc/API

2022-06-02 09:17 UTC, mattsse commented on src/anvil/rpcMethods.md
> +`evm_snapshot`
these are all coming from ganache we should link here to https://github.com/trufflesuite/ganache-cli-archive/blob/master/README.md

2022-06-02 09:17 UTC, mattsse commented on src/anvil/rpcMethods.md
> +`txpool_content`
these are geth endpoints, we should link here to https://geth.ethereum.org/docs/rpc/ns-txpool

2022-06-02 09:17 UTC, mattsse commented on src/anvil/transportLayers.md
> +```
I don't think this needs to be a separate file

2022-06-02 09:17 UTC, mattsse commented on src/anvil/rpcMethods.md
> +### Custom Methods
need to add info that the `anvil` namespace is an alias for `hardhat`

2022-06-02 21:41 UTC, onbjerg requested changes
Some structural comments:

- All of this should probably live in a command reference like Forge and Cast have, since this is reference documentation and not really guides. The place where this content was put is more geared towards the latter.
- Almost all of these can be merged into one overall Forge reference document. I also don't think we need to list out every standard JSONRPC method we support, only the differences/Anvil specific ones

Thanks for taking a stab at this :smile:

2022-06-02 21:41 UTC, onbjerg commented on src/SUMMARY.md
> +- [Supported RPC Methods](./anvil/rpcMethods.md)
All of these files should be named in line with the other files using lowercase and with `-` as a separator

2022-06-02 21:41 UTC, onbjerg commented on src/anvil/AnvilFlags.md
> +## Anvil Flags
This is better suited for a command reference like Forge and Cast, and should live in `src/reference` as well as follow the general structure that Cast and Forge does

2022-06-02 21:41 UTC, onbjerg commented on src/anvil/AnvilFlags.md
> +            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - 5: Print execution and setup traces for all tests
```suggestion
 &nbsp;&nbsp;&nbsp;&nbsp; Verbosity levels:  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - 2: Print logs for all tests  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - 3: Print execution traces for failing tests  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - 4: Print execution traces for all tests, and setup traces for failing tests  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - 5: Print execution and setup traces for all tests
```

2022-06-02 21:41 UTC, onbjerg commented on src/anvil/AnvilFlags.md
> +```
````suggestion
  ```sh
  anvil --accounts 15 --balance 300
  ```
````

2022-06-02 21:41 UTC, onbjerg commented on src/anvil/AnvilFlags.md
> +```
````suggestion
  ```sh
  anvil --sender 0xC8479C45EE87E0B437c09d3b8FE8ED14ccDa825E
  ```
````

2022-06-02 21:41 UTC, onbjerg commented on src/anvil/AnvilFlags.md
> +```
````suggestion
  ```sh
  anvil --order fifo
  ```
````

2022-06-02 21:41 UTC, onbjerg commented on src/anvil/MiningModes.md
> +```
````suggestion
```sh
# Produces a new block every 10 seconds
anvil --block-time 10
```
````

2022-06-02 21:41 UTC, onbjerg commented on src/anvil/MiningModes.md
> +```
````suggestion
```sh
# Enables never mining mode
anvil --no-mining
```
````

2022-06-02 21:41 UTC, onbjerg commented on src/anvil/rpcMethods.md
> +`web3_clientVersion`
Please put this in a list

2022-06-02 21:41 UTC, onbjerg commented on src/anvil/rpcMethods.md
> +`Anvil` namespace is an alias for `hardhat`, just like in [this](https://hardhat.org/hardhat-network/reference#hardhat-network-methods) Hardhat documentation.
```suggestion
The `anvil_*` namespace is an alias for `hardhat`. For more info, refer to the [Hardhat documentation](https://hardhat.org/hardhat-network/reference#hardhat-network-methods).
```

2022-06-03 14:19 UTC, Leutwiler commented on src/anvil/rpcMethods.md
> +`web3_clientVersion`
The new version has the standard methods on a listed format. I don't think it looks good for the custom and special methods, as they have an explanation underneath them, but if you think it's necessary to also list them, I can do it.

What's your opinion about it?

2022-06-03 15:15 UTC, Leutwiler commented
> * All of this should probably live in a command reference like Forge and Cast have, since this is reference documentation and not really guides. The place where this content was put is more geared towards the latter.
> * Almost all of these can be merged into one overall Forge reference document. I also don't think we need to list out every standard JSONRPC method we support, only the differences/Anvil specific ones

I got a little bit lost with the "all of this" and "almost all of these". As far as I could understand, I changed the Anvil Flags part to References and merged the other files in one, which I'm gonna keep in the same place.

I really think we should keep with the standard RPC methods. From a beginner's perspective, I didn't know what were RPC methods and which were the standard methods before I started to write this documentation, so I think this part may help new people who are not familiar with this topic. Hardhat's documentation also covers their available standard RPC methods in the same format, that's also why I decided to keep them. What do you think about that?

> * The file names should follow the structure of pre-existing files (lowercase and `-` as a seperator)
This and all the other comments you wrote are already done! :)

2022-06-05 09:26 UTC, onbjerg requested changes
Still a bit to go - the structure should follow that of Forge and Cast in the reference :smile: 

For an idea of what I mean, see https://github.com/foundry-rs/book/pull/359

Additionally, mining modes and RPC methods could also be in the description of the commnad reference - see for example the longer-form description of forge build

2022-06-05 09:26 UTC, onbjerg commented on src/SUMMARY.md
> +    - [Server Options Flags](./reference/anvil/anvil-server.md)
This should just be 

```suggestion
  - [`anvil` Reference](./reference/anvil/README.md)
```

And all of the flags and an overview should be in the README, just like we have for Cast and Forge

2022-06-05 09:26 UTC, onbjerg commented on src/reference/README.md
> +- [anvil Flags](./anvil/)
```suggestion
- [anvil Reference](./anvil/)
```

2022-06-05 09:26 UTC, onbjerg commented on src/reference/anvil/README.md
> +## anvil Flags
```suggestion
## anvil Reference
```

2022-06-05 19:57 UTC, Leutwiler commented
I think everything is fixed now! If there are any other issues, just let me know! 😄

2022-06-06 11:27 UTC, onbjerg approved these changes
Thanks for this and sorry about all the nits! :smile:

2022-06-06 11:27 UTC, onbjerg commented on src/reference/anvil/README.md
> +```
````suggestion
```sh
````

2022-06-06 11:28 UTC, merged

2022-06-06 11:34 UTC, mattsse commented
thanks so much @Leutwiler