Added a solidity scripting tutorial
foundry-rs/book pull request #370
Opened 2022-06-09 22:54 UTC by Perelyn-sama

Here as promised @gakonst. Sorry, it took more than 48 hrs.

As usual, I'm open to corrections.

2022-06-10 09:15 UTC, onbjerg requested changes
Some wording stuff and some minor nits - let me know what you think :)

2022-06-10 09:15 UTC, onbjerg commented on src/tutorials/solidity-scripting.md
> +Before solidity scripting was introduced we only had one way to deploy contracts in Foundry to either mainnet or any other chain which was [`forge create`](../reference/forge/forge-create.md), ideall
Doesn't need to be exactly like this, but I found the sentence overly verbose

```suggestion
Solidity scripting is a way to declaratively deploy contracts using Solidity, instead of using the more limiting and less user friendly [`forge create`](../reference/forge/forge-create.md).
```

2022-06-10 09:15 UTC, onbjerg commented on src/tutorials/solidity-scripting.md
> +Solidity scripting is just like the regular scripts you write when working with tools like Hardhat, what makes solidity scripting different is the fact that instead of writing scripts in for instance
Again; doesn't need to be exactly like this, but I'd say the major differences are:

- That it is written in Solidity
- That you have access to the Foundry EVM backend, so you can do things like dry-running before actually deploying, and you have access to a fuller range of features (i.e. all cheatcodes)

```suggestion
Solidity scripts are like the scripts you write when working with tools like Hardhat; what makes Solidity scripting different is that they are written in Solidity instead of JavaScript, and they are run on the fast Foundry EVM backend, which provides dry-run capabilities.
```

2022-06-10 09:15 UTC, onbjerg commented on src/tutorials/solidity-scripting.md
> +![Untitled](../images/solidity-scripting%20/set-up-commands.png)
Please provide a better alt text than untitled :smile:

2022-06-10 09:15 UTC, onbjerg commented on src/tutorials/solidity-scripting.md
> +![Untitled](../images/solidity-scripting%20/compile-successful.png)
Same as above

2022-06-10 09:15 UTC, onbjerg commented on src/tutorials/solidity-scripting.md
> +If you get this, it's the contract compiled successfully.
Maybe hoist it above the image?

```suggestion
If your output looks like this, the contracts successfully compiled.
```

2022-06-10 09:15 UTC, onbjerg commented on src/tutorials/solidity-scripting.md
> +We’re going to deploy the `NFT` contract to the rinkeby testnet but to do this we’ll need some variables like a Rinkeby Rpc Url, the private key of an account that’s funded with Rinkeby Eth and an Et
```suggestion
We’re going to deploy the `NFT` contract to the Rinkeby testnet, but to do this we’ll need to configure Foundry a bit, by setting things like a Rinkeby RPC URL, the private key of an account that’s funded with Rinkeby Eth, and an Etherscan key for the verification of the NFT contract.
```

2022-06-10 09:15 UTC, onbjerg commented on src/tutorials/solidity-scripting.md
> +```
```suggestion

```

Doesn't matter much IMO - people can just create the file in whatever editor they want

2022-06-10 09:15 UTC, onbjerg commented on src/tutorials/solidity-scripting.md
> +Next, we have to create a folder and name it `script` then create a file in it called `NFT.s.sol`, the contents of NFT.s.sol should look like this:
```suggestion
Next, we have to create a folder and name it `script` and create a file in it called `NFT.s.sol`. This is where we will create the deployment script itself.

The contents of `NFT.s.sol` should look like this:
```

2022-06-10 09:15 UTC, onbjerg commented on src/tutorials/solidity-scripting.md
> +This is what a script in Foundry looks like, now let’s take a walkthrough of the code and what it actually means and does.
```suggestion
Now let’s read through the code and figure out what it actually means and does.
```

2022-06-10 09:15 UTC, onbjerg commented on src/tutorials/solidity-scripting.md
> +Remember even if it’s a script it still works like a smart contract but is never deployed, so just like any other smart contract written in solidity the `pragma version` has to be specified.
```suggestion
Remember even if it’s a script it still works like a smart contract, but is never deployed, so just like any other smart contract written in Solidity the `pragma version` has to be specified.
```

2022-06-10 09:15 UTC, onbjerg commented on src/tutorials/solidity-scripting.md
> +Just like how in Foundry tests we import `forge-std/Test.sol` to get utilities we’ll in our tests, that’s how we import `forge-std/Script.sol` in our scripts to get utilities we’ll need while writing
```suggestion
Just like we may import Forge Std to get testing utilities when writing tests, Forge Std also provides some scripting utilities that we import here.
```

2022-06-10 09:15 UTC, onbjerg commented on src/tutorials/solidity-scripting.md
> +We create a contract called `MyScript` and it inherits `Script` which is from the file we imported earlier.
```suggestion
We create a contract called `MyScript` and it inherits `Script` from Forge Std.
```

2022-06-10 09:15 UTC, onbjerg commented on src/tutorials/solidity-scripting.md
> +For script smart contracts we only need one function and that’s the run function, think about it like the main function in a Hardhat script written in JavaScript. We deploy our contracts in this func
```suggestion
By default, scripts are executed by calling the function named `run`, our entrypoint.
```

2022-06-10 09:15 UTC, onbjerg commented on src/tutorials/solidity-scripting.md
> +This Foundry cheat code is uses the address that calls the `Script` contract to create a transaction that can later be signed and sent on chain. In other words we’ll use it create the deployment tran
```suggestion
This is a special cheatcode that records calls and contract creations made by our main script contract. Later, we will broadcast these transactions to deploy our NFT contract.
```

2022-06-10 09:15 UTC, onbjerg commented on src/tutorials/solidity-scripting.md
> +You should be familiar with this part, all it does is create an instance of our NFT contract which will be deployed once we run the script.
```suggestion
Here we just create our NFT contract. Because we called `vm.startBroadcast()` before this line, the contract creation will be recorded by Forge, and as mentioned previously, we can broadcast the transaction to deploy the contract on-chain.
```

2022-06-10 09:15 UTC, onbjerg commented on src/tutorials/solidity-scripting.md
> +![Untitled](../images/solidity-scripting%20/contract-verified.png)
Better alt text please :smile:

2022-06-10 09:15 UTC, onbjerg commented on src/tutorials/solidity-scripting.md
> +It’s going to take some time not up to a minute, at the bottom of your terminal you should see something like this:
```suggestion
Forge is going to run our script and broadcast the transactions for us - this can take a little while, since Forge will also wait for the transaction receipts. You should see something like this after a minute or so:
```

2022-06-10 09:42 UTC, Perelyn-sama commented
Thanks man, you're the best. I'll go read them now.

2022-06-10 15:15 UTC, Perelyn-sama commented on src/tutorials/solidity-scripting.md
> +```
Sorry, I'm a sucker for details. haha

2022-06-10 15:17 UTC, Perelyn-sama commented on src/tutorials/solidity-scripting.md
> +![Untitled](../images/solidity-scripting%20/contract-verified.png)
I'm sorry about that. I work on it.

2022-06-11 18:35 UTC, gakonst requested changes
LGTM - please remove the unnecessary changes as flagged

2022-06-11 19:28 UTC, Perelyn-sama commented
Okay, I'll get on it.

2022-06-11 19:32 UTC, Perelyn-sama commented on src/SUMMARY.md
> +    <!-- - [Generating Documentation]() !-->
Sorry, my formatter did that.

2022-06-11 19:48 UTC, gakonst approved these changes

2022-06-11 19:49 UTC, merged

2022-06-11 19:50 UTC, Perelyn-sama commented
When I wrote this tutorial, the `script` folder was not made on default when you run `forge init`.

Now It is, I'm not sure if I should rewrite the part I asked users to create a `script` folder or just add a note that says "if you have the `script` folder already skip this part.

What do you think @gakonst ?

2022-06-11 19:51 UTC, Perelyn-sama commented
oh, it's already merged.

2022-06-11 19:52 UTC, gakonst commented
Sure - go for it. Think of this as the tutorial you'd love to have for yourself if you were starting out now :)

2022-06-12 14:12 UTC, fps8k commented
### **PROUD OF YOU, PERELYN 🎉!!**