add base-fee alias
foundry-rs/book pull request #399
Opened 2022-06-23 22:06 UTC by 0xvv

closes https://github.com/foundry-rs/book/issues/391

2022-06-24 21:34 UTC, onbjerg requested changes

2022-06-24 21:34 UTC, onbjerg commented on src/reference/anvil/README.md
> +`--base-fee, --block-base-fee-per-gas <FEE>`
```suggestion
`--base-fee`  
`--block-base-fee-per-gas <FEE>`  
```

Same for the other change

2022-06-25 16:50 UTC, 0xvv commented on src/reference/anvil/README.md
> +`--base-fee, --block-base-fee-per-gas <FEE>`
It does look better, i was trying to stay consistent with what was above, but those were one letter aliases

2022-06-27 06:09 UTC, onbjerg approved these changes

2022-06-27 06:09 UTC, merged