docs: document struct coded and add examples
foundry-rs/book pull request #406
Opened 2022-06-28 17:15 UTC by mattsse

document struct ABI codec and add examples to cast (sig, send)

ref https://github.com/foundry-rs/foundry/pull/2151

2022-06-28 17:20 UTC, onbjerg commented
I think the struct encoding file needs to be in summary.md to be rendered

2022-06-28 18:06 UTC, mattsse commented
was the line indent lol

2022-06-28 23:09 UTC, gakonst commented
Can we also make it work so that people can copy/paste struct definitions in line? `cast call 0x1234 `struct Foo { address x; int256 y; }` or do we think it doesn't make sense?

2022-06-29 06:35 UTC, onbjerg requested changes
Got some structural nits/phrasing but also have one comment for one of the examples. Will just batch commit the nits except for the one I'm unsure about

2022-06-29 06:35 UTC, onbjerg commented on src/misc/README.md
> +- [struct encoding](./struct-encoding.md)
```suggestion
- [Struct encoding](./struct-encoding.md)
```

2022-06-29 06:35 UTC, onbjerg commented on src/misc/struct-encoding.md
> +#### Struct Encoding
```suggestion
## Struct Encoding
```

2022-06-29 06:35 UTC, onbjerg commented on src/misc/struct-encoding.md
> +Structs are custom defined types that can group several variables:
```suggestion
Structs are user defined types that can group several variables:
```

2022-06-29 06:35 UTC, onbjerg commented on src/misc/struct-encoding.md
> +Structs map to the ABI type "tuple", See also [Mapping Solidity to ABI types](https://docs.soliditylang.org/en/latest/abi-spec.html#mapping-solidity-to-abi-types)
```suggestion
Solidity structs map to the ABI type "tuple". For more information on how Solidity types map to ABI types see [Mapping Solidity to ABI types](https://docs.soliditylang.org/en/latest/abi-spec.html#mapping-solidity-to-abi-types) in the Solidity documentation.
```

2022-06-29 06:35 UTC, onbjerg commented on src/misc/struct-encoding.md
> +Structs are therefor encoded and decodes as tuples. So `MyStruct` is a `(address,uint256)` tuple when it comes to the ABI spec.
```suggestion
Structs are therefore encoded and decodes as tuples. So the struct we defined above, `MyStruct`, maps to the tuple `(address,uint256)` in terms of the ABI.
```

2022-06-29 06:35 UTC, onbjerg commented on src/misc/struct-encoding.md
> +For example the ABI of
```suggestion
Let's see how this works in a contract:
```

2022-06-29 06:35 UTC, onbjerg commented on src/misc/struct-encoding.md
> +results in the following ABI json object:
```suggestion
The ABI of the `f` function in this contract is:
```

2022-06-29 06:35 UTC, onbjerg commented on src/misc/struct-encoding.md
> +The function `f` takes 1 input of type `tuple` with two components of type `address` and `uint256`.
```suggestion
which reads: The function `f` takes 1 input of type `tuple` with two components of type `address` and `uint256`.
```

2022-06-29 06:35 UTC, onbjerg commented on src/reference/cast/cast-send.md
> +```
````suggestion
    Structs are encoded as tuples (see [struct encoding](./reference/common/struct-encoding.md))

    ```sh
    cast send --ledger 0x... "myfunction((address,uint256))" 0x... 1
    ```
````

Also, would this not be e.g. `cast send "myfunction((address,uint256))" 0x... "(0x..., 1)"`?

2022-06-29 06:35 UTC, onbjerg commented on src/reference/cast/cast-sig.md
> +```
````suggestion
    Structs are encoded as tuples (see [struct encoding](./reference/common/struct-encoding.md)).

    ```sh
    cast sig "myfunction((address,uint256))"
    ```
````

2022-06-29 11:38 UTC, mattsse commented on src/reference/cast/cast-send.md
> +```
```console

USAGE:
    cast send [OPTIONS] <TO> [ARGS]

ARGS:
    <TO>
            The destination of the transaction.

    <SIG>
            The signature of the function to call.

    <ARGS>...
            The arguments of the function to call.

```

so `cast send <to> <sig> <args>` is correct here

2022-06-29 12:11 UTC, onbjerg commented on src/reference/cast/cast-send.md
> +```
Ye but args in this case would be "(0x..., 1)". The current example is:

```
cast send --ledger 0x... "myfunction((address,uint256))" 0x... 1
```

In other words:

Send using Ledger addr 0x..., call "myfunction" at address 0x... with argument 1?

2022-06-29 12:41 UTC, mattsse commented on src/reference/cast/cast-send.md
> +```
guess that makes sense, I only copy pasted the example tbh

2022-06-29 12:52 UTC, onbjerg approved these changes

2022-06-29 12:52 UTC, onbjerg commented
Can merge when the base PR is merged

2022-06-29 15:05 UTC, merged