Cheatcode Documentation Revision
foundry-rs/book pull request #470
Opened 2022-07-23 13:52 UTC by The-Arbiter

Hi,

I have made some revisions to the `cheatcodes` section following [this discussion](https://twitter.com/0xArbiter/status/1550126535440379911) on Twitter with Bjerg.

### Why did you make these changes?

I felt that there wasn't sufficient documentation surrounding the forge-std 'cheatcodes', which was weird considering they're meant for DX improvements.

### What did you do?

- Refactored parts of the document to make it easier to read
- Added in a section explaining how to exclude the cheatcode address from fuzz testing (this and the precompile addresses personally cost me 3 days of dev time when I was learning Foundry, luckily a fellow dev explained what I needed to do)
- Added a link to the Forge Standard Library 'cheatcodes' directly from this document
- Added a link to the forge-std GitHub for those who want to see how the 'cheatcodes' work under the hood, to avoid confusion

### What is controversial about this?

Calling the forge-std functions 'cheatcodes' is a bit controversial since technically they're just fancy wrappers, so I tried to make that clear in my revision.

Explaining how to use `vm.assume` to exclude the cheatcode address might be a bit controversial since it's not technically in the same theme as cheatcodes (the topic) but this is the most prominent mention of the cheatcode address (0x7109709ECfa91a80626fF3989D68f67F5b1DD12D) and so where someone encountering an error with this address would end up when searching the docs.

Let me know what you guys think.

Cheers,
Arby

2022-07-24 18:55 UTC, onbjerg requested changes
some nits, lmk

2022-07-24 18:55 UTC, onbjerg commented on src/cheatcodes/README.md
> +Cheatcodes are made available through use of the cheatcode address (`0x7109709ECfa91a80626fF3989D68f67F5b1DD12D`). If you encounter errors for this address when using fuzzed addresses in your tests,
Let's add this as a note box like we do on docs elsewhere. An example can be found [here](https://book.getfoundry.sh/getting-started/installation) (at the bottom)

2022-07-24 18:55 UTC, onbjerg commented on src/cheatcodes/README.md
> +```
Should be in the box mentioned in above comment)

2022-07-24 18:55 UTC, onbjerg commented on src/cheatcodes/README.md
> +```
```suggestion
You can also access cheatcodes easily via `vm` available in Forge Standard Library's [`Test`](../reference/forge-std/#forge-stds-test) contract.
```

this might be a bit controversial but I don't think we need to list out the example here (can refer to the docs linked)

2022-07-24 18:55 UTC, onbjerg commented on src/cheatcodes/README.md
> +Forge-std implements 'cheatcodes' through a wrapper which combines multiple standard cheatcodes to improve development experience. These are not technically cheatcodes, but rather a composition of Fo
```suggestion
Forge Std implements wrappers around cheatcodes, which combine multiple standard cheatcodes to improve development experience. These are not technically cheatcodes, but rather compositions of Forge's cheatcodes.
```

2022-07-24 18:55 UTC, onbjerg commented on src/cheatcodes/README.md
> +You can view the list of Forge Standard Library's 'cheatcodes' [in the references section](../reference/forge-std/std-cheats.md) and see how each of them uses the Forge cheatcodes in the [Forge-std s
```suggestion
You can view the list of Forge Standard Library's cheatcode wrappers [in the references section](../reference/forge-std/std-cheats.md). You can reference the [Forge Std source code](https://github.com/foundry-rs/forge-std/blob/master/src/Test.sol) to learn more about how the wrappers work under the hood.
```

2022-07-24 20:28 UTC, The-Arbiter commented on src/cheatcodes/README.md
> +```
Have put > before each line - assuming this is how it works even for code renders since that's how Obsidian renders it for me.

2022-07-24 20:33 UTC, The-Arbiter commented
Okay have done these lmk if there is anything else.

Arby

2022-07-25 14:57 UTC, onbjerg approved these changes

2022-07-25 14:57 UTC, merged

2022-07-25 14:57 UTC, onbjerg commented
@all-contributors add @The-Arbiter for docs