Restructure forking cheatcodes reference
foundry-rs/book pull request #471
Opened 2022-07-23 22:57 UTC by neodaoist

Addresses https://github.com/foundry-rs/book/issues/454

Overview of changes:
- Create individual reference pages for each of the 5 forking-related cheatcodes
- (Attempt to) explain holistically both approaches to fork testing in overview page (forking mode/CLI vs. forking cheatcodes/Solidity)
- Make note of soon-to-change storage behavior (coming with https://github.com/foundry-rs/foundry/pull/2301) in overview page
- Rename and move fork testing overview page to Advanced Testing section
- Make note of cheatcode-based approach in Forking Mode tutorial

Shoutout to @mattsse who I believe did most of this work 🙌 the forking cheatcodes are super powerful! My PR is mostly just reorganizing the docs and trying to simplify/clarify in some places.

2022-07-24 18:50 UTC, onbjerg requested changes
Thanks for this :) Some comments

2022-07-24 18:50 UTC, onbjerg commented on src/SUMMARY.md
>  - [Advanced Testing](./forge/advanced-testing.md)
Can you check if this page needs to be updated? And perhaps also `forge/README.md` if it exists. IIRC both of them list out the docs in the coming section

2022-07-24 18:50 UTC, onbjerg commented on src/forge/fork-testing.md
> +- **Forking Cheatcodes** — create, select, and manage multiple forks directly in Solidity test code via [forking cheatcodes](../cheatcodes/forking.md)
Can we add links to the sections here? IIRC they will be named `#forking-mode` and `#forking-cheatcodes`

2022-07-24 18:50 UTC, onbjerg commented on src/forge/fork-testing.md
> +> The current read/write behavior will change soon, with completely separated storage sections for each fork. The docs will be updated to reflect this change and illustrate usage.
```suggestion
>ℹ️ **Important Note**
>
> The current read/write behavior will change soon, with completely separated storage sections for each fork. The docs will be updated to reflect this change and illustrate usage.
```

2022-07-24 18:50 UTC, onbjerg commented on src/tutorials/testing-on-a-forked-network.md
> +By combining [Anvil][anvil] and [Cast][cast], you can fork and test by interacting with contracts on a real network. The goal of this tutorial is to show you how to transfer Dai tokens from someone w
IIRC this tutorial is about using Cast/Anvil, not fork, so this line does not apply for this tutorial. We should probably rename the tutorial though since it is a bit misleading

2022-07-24 21:17 UTC, neodaoist commented on src/forge/fork-testing.md
> +- **Forking Cheatcodes** — create, select, and manage multiple forks directly in Solidity test code via [forking cheatcodes](../cheatcodes/forking.md)
Good call =) Done 👍

2022-07-24 21:19 UTC, neodaoist commented on src/forge/fork-testing.md
> +> The current read/write behavior will change soon, with completely separated storage sections for each fork. The docs will be updated to reflect this change and illustrate usage.
All in the info box now 👍

2022-07-24 21:26 UTC, neodaoist commented on src/tutorials/testing-on-a-forked-network.md
> +By combining [Anvil][anvil] and [Cast][cast], you can fork and test by interacting with contracts on a real network. The goal of this tutorial is to show you how to transfer Dai tokens from someone w
Hmm yeah, good point. I will remove the cheatcode info box, and take a crack at renaming this tutorial.

After this PR, thinking I can write a tutorial demonstrating the DAI transfer example using the two forge forking approaches.

2022-07-24 21:36 UTC, neodaoist commented on src/SUMMARY.md
>  - [Advanced Testing](./forge/advanced-testing.md)
Think we're good here. Verified link is correct in `SUMMARY.md` and doesn't exist in `README.md`.

FYI I had moved the main forking overview from Basic to Advanced Testing section, but I moved back to the basic section where it was.

2022-07-24 21:39 UTC, neodaoist commented
@onbjerg made few updates to reflect your feedback. Thank you for the review! 🙏

2022-07-25 15:04 UTC, onbjerg commented on src/tutorials/testing-on-a-forked-network.md
> +# Testing on a Forked Network
This file is empty now, was it supposed to be deleted?

2022-07-25 15:51 UTC, neodaoist commented on src/tutorials/testing-on-a-forked-network.md
> +# Testing on a Forked Network
Yes, deleted now

2022-07-25 15:53 UTC, onbjerg commented
Thanks for this! :smile: @all-contributors add @neodaoist for docs

2022-07-25 15:54 UTC, merged