Document console.log format specifiers
foundry-rs/book pull request #472
Opened 2022-07-24 03:33 UTC by Inphi

Document console.log string format specifiers implemented in https://github.com/foundry-rs/foundry/pull/2313.

2022-07-24 10:53 UTC, mattsse approved these changes
ty!

smol suggestion

2022-07-24 10:53 UTC, mattsse commented on src/reference/forge-std/console-log.md
> +The `console.log()` method returns a formatted string using the first argument as a printf-like format string which can contain zero or more format specifiers. Each specifier is replaced with the con
```suggestion
The `console.log()` method prints a formatted string using the first argument as a printf-like format string which can contain zero or more format specifiers. Each specifier is replaced with the converted value from the corresponding argument. Supported specifiers are:
```

2022-07-24 18:45 UTC, onbjerg requested changes
Need my comments for tests to pass

Additionally, could you link to the page [here](https://github.com/foundry-rs/book/blob/1adb7196fa57da5f5a3b1274f4fbda5e4b51130f/src/reference/forge-std/README.md) and [here](https://github.com/foundry-rs/book/blob/1adb7196fa57da5f5a3b1274f4fbda5e4b51130f/src/faq.md) (in the relevant sections)?

2022-07-24 18:45 UTC, onbjerg commented on src/reference/forge-std/console-log.md
> +```
````suggestion
```solidity
````

2022-07-24 18:45 UTC, onbjerg commented on src/reference/forge-std/console-log.md
> +```
````suggestion
```solidity
````

2022-07-24 18:45 UTC, onbjerg commented on src/reference/forge-std/console-log.md
> +```
````suggestion
```solidity
````

2022-07-25 14:54 UTC, onbjerg approved these changes

2022-07-25 14:55 UTC, onbjerg commented
@all-contributors add @Inphi for docs

2022-07-25 14:55 UTC, merged