doc: add best practices
foundry-rs/book pull request #686
Opened 2022-10-27 20:10 UTC by mds1

Leaving this as a draft to collect feedback on the content, cc @odyslam @lucas-manuel @gakonst

2022-10-27 20:23 UTC, odyslam commented
@mds1 I left some replies in the comments that were not resolved. Did you address them (include/not include) or should I move them here.

2022-10-27 20:25 UTC, mds1 commented
Yea let's move them here, I don't think all were addressed, thanks!

2022-11-01 03:04 UTC, odyslam requested changes

2022-11-01 03:04 UTC, odyslam commented on src/tutorials/best-practices.md
> +1. Be consistent with test naming, as it's helpful for filtering tests (e.g. for gas reports you might want to filter out revert tests). When combining naming conventions, keep them alphabetical.
Lucas suggestion: `test_functionName_description`

I am in favour

2022-11-01 03:04 UTC, odyslam commented on src/tutorials/best-practices.md
> +- Write fork tests to verify the correct behavior with existing deployed contract.
Where should fork tests live?

IMHO, they should not be run as often as unit tests, as they would slow down the developer.

2022-11-01 11:01 UTC, lucas-manuel commented on src/tutorials/best-practices.md
> +1. Always use "absolute" paths for imports, i.e. paths relative to the repo root. This makes it easier to see where files are from and reduces churn when moving files around.
`import { MapleLoan as Loan } from "../modules/loan/contracts/MapleLoan.sol";`

2022-11-01 11:02 UTC, lucas-manuel commented on src/tutorials/best-practices.md
> +1. Always use "absolute" paths for imports, i.e. paths relative to the repo root. This makes it easier to see where files are from and reduces churn when moving files around.
This was something we adopted a while back because we kept having conflicting submodule versions, so this was a way around that. Also natively works with the solc static compiler in VSCode without settings updates but thats not a big deal

2022-11-01 11:03 UTC, lucas-manuel commented on src/tutorials/best-practices.md
> +1. Be consistent with test naming, as it's helpful for filtering tests (e.g. for gas reports you might want to filter out revert tests). When combining naming conventions, keep them alphabetical.
I like this pattern a lot because it makes searching for tests super easy. I do get @mds1s point around integration tests, but maybe this could be the unit test convention?

2022-11-01 11:05 UTC, lucas-manuel commented on src/tutorials/best-practices.md
> +1. Don't forget invariant tests! For the assertion string, use a verbose english description of the invariant: `assertEq(x + y, z, "Invariant violated: the sum of x and y must always equal z")`.
Thinking about talking about actor based patterns etc here

2022-11-01 11:11 UTC, lucas-manuel commented on src/tutorials/best-practices.md
> +- Write _positive_ unit tests for things that the code should handle. Validate _all_ state that changes from these tests.
Maybe we should explicitly mention that each code path should have a separate unit test?

2022-11-01 11:11 UTC, lucas-manuel commented on src/tutorials/best-practices.md
> +To test `internal` functions, write a harness contract that inherits from the contract under test (CuT). Harness contracts that inherit from the CuT expose the `internal` functions as `external` ones
Idk where this would go, but one cool thing we've been doing is using contracts (idk whether to refer to them as harnesses or mocks in this context) in integration fuzzing tests to allow for easier fuzzing. An example is a totalAssets setter that is added to a contract that inherits a 4626 implementation.

`vm.etch` can be used to replace this in the broader context of a protocol and fuzzing can be done more easily/effectively in an integration test this way

2022-11-01 11:11 UTC, lucas-manuel commented on src/tutorials/best-practices.md
> +
Should we add a section on events assertions?

2022-11-01 11:11 UTC, lucas-manuel commented on src/tutorials/best-practices.md
> +1. For testing `MyContract.sol`, the test file should be `MyContract.t.sol`. For testing `MyScript.s.sol`, the test file should be `MyScript.t.sol`.
Also we should fix this list as they are currently all `1.`

2022-11-01 11:11 UTC, lucas-manuel commented on src/tutorials/best-practices.md
> +Another use case for this is tracking data that you would not track in production to help test invariants. For example, you might store a list of all token holders to simplify validation of the invar
Yeah I think we should add a dedicated section about ghost variables to the invariant documentation

2022-11-01 11:11 UTC, lucas-manuel commented on src/tutorials/best-practices.md
> +Another use case for this is tracking data that you would not track in production to help test invariants. For example, you might store a list of all token holders to simplify validation of the invar
We can also discuss some of the other concepts from that talk (naive implementations etc)

2022-11-01 13:27 UTC, mds1 commented on src/tutorials/best-practices.md
> +1. Always use "absolute" paths for imports, i.e. paths relative to the repo root. This makes it easier to see where files are from and reduces churn when moving files around.
We just use the default remappings most of the time, occasionally may add others. My version @lucas-manuel's example would be something like:

```solidity
import { MapleLoan as Loan } from "src/loan/contracts/MapleLoan.sol";
```

However, @mattsse has mentioned these absolute paths can cause issues sometimes, and I've also noticed slither can't handle them. Even though slither should handle them, maybe we should remove this line since they are sometimes troublesome?

2022-11-01 13:35 UTC, mds1 commented on src/tutorials/best-practices.md
> +1. Be consistent with test naming, as it's helpful for filtering tests (e.g. for gas reports you might want to filter out revert tests). When combining naming conventions, keep them alphabetical.
What's the rationale for this convention (`test_functionName_description`) vs. "contract name = function under test, test names are spec of that function" as currently proposed? The logic I have for the current approach is that in JS/TS tests with hardhat, structuring contract unit tests such that describe blocks are functions, and `it('whatever')` is a requirement of that function is common, e.g. see [Uni V3 tests](https://github.com/Uniswap/v3-core/blob/main/test/UniswapV3Pool.spec.ts#L159). This makes that transition seamless.

It still makes searching for tests easy: just search for `contract FunctionName` instead of `test_functionName`

Without it, what becomes the "describe" block for a function? I guess you can create arbitrary scopes with comments, but that feels a bit grosser

2022-11-01 13:41 UTC, mds1 commented on src/tutorials/best-practices.md
> +- Write fork tests to verify the correct behavior with existing deployed contract.
These days I actually feel pretty strongly that fork tests should not get special treatment, and should be used liberally. Here's why:

1. Mocks are arguably a remnant of closed-source web2 dev—you have to mock API responses because the code for that API isn't open source so you can't just run it locally. But for blockchains that's not true: any code you're interacting with that's already deployed can be locally executed and even modified for free. So why introduce the risk of a wrong mock if you don't need to?

2. A big reason to avoid forking and use mocks is that fork tests are slow. But this is not true. By pinning to a block number, RPC responses are cached and only the first run is slower, subsequent runs should be very fast (see https://github.com/mds1/convex-shutdown-simulation/ as proof, 7 minutes for remote RPC, 13s for a local RPC, half a second with cached results). Alchemy and Infura both offer free archive data, so pinning to a block shouldn't be problematic either.

2022-11-01 14:17 UTC, mds1 commented on src/tutorials/best-practices.md
> +- Write _positive_ unit tests for things that the code should handle. Validate _all_ state that changes from these tests.
I like that, just added 888a768 with this info

2022-11-01 14:21 UTC, mds1 commented on src/tutorials/best-practices.md
> +To test `internal` functions, write a harness contract that inherits from the contract under test (CuT). Harness contracts that inherit from the CuT expose the `internal` functions as `external` ones
> An example is a totalAssets setter that is added to a contract that inherits a 4626 implementation.

The way we've done this is to add test helper methods like `function supply(address from, uint256 amount)` that deals token to `from`, then uses prank to execute approvals and supply tokens to the protocol to increase `totalAssets`. Both approaches are definitely valid and have different tradeoffs / depends on the specifics of your protocol which is best. 

I think this could fall under the `Workaround Function` header if you wanted to add a few sentences

2022-11-01 14:21 UTC, odyslam commented on src/tutorials/best-practices.md
> +
What tips do you have in mind?

2022-11-01 14:23 UTC, mds1 commented on src/tutorials/best-practices.md
> +
What exactly do you have in mind here? One thing I can think of is always using `vm.expectEmit(true, true, true, true)` unless you have a strong reason to use `false` somewhere. Because:
1. This ensures you test everything in your event.
2. If you add a topic (i.e. a new indexed param), it's now tested by default.
3. Even if you only have 1 topic, the extra `true` args don't hurt

2022-11-01 14:24 UTC, mds1 commented on src/tutorials/best-practices.md
> +1. For testing `MyContract.sol`, the test file should be `MyContract.t.sol`. For testing `MyScript.s.sol`, the test file should be `MyScript.t.sol`.
Heh I actually did that on purpose because markdown automatically renders the numbers sequentially, so using `1.` everywhere makes it easier to reorder/add/remove things without the numbers getting out of sync

2022-11-01 14:26 UTC, mds1 commented on src/tutorials/best-practices.md
> +Another use case for this is tracking data that you would not track in production to help test invariants. For example, you might store a list of all token holders to simplify validation of the invar
I agree, I thought there were some great topics in that talk and am down to document them. Should just expand this "workarounds" section to include more info? (Feel free to push a commit with this info, or if you don't have permission can open a PR into this branch)

2022-11-03 04:00 UTC, odyslam commented on src/tutorials/best-practices.md
> +1. Always use "absolute" paths for imports, i.e. paths relative to the repo root. This makes it easier to see where files are from and reduces churn when moving files around.
I started using full paths, and I have to say that it looks much cleaner than mentally having to work out the `../../` and mentally count how many times you have to go back, etc etc.

That being said, other tools do have an issue with those.

I really don't know what to suggest.

2022-11-03 04:04 UTC, odyslam commented on src/tutorials/best-practices.md
> +- Write fork tests to verify the correct behavior with existing deployed contract.
Okay, agree here. 

Let's do that

2022-11-03 04:04 UTC, odyslam commented on src/tutorials/best-practices.md
> +1. Don't forget invariant tests! For the assertion string, use a verbose english description of the invariant: `assertEq(x + y, z, "Invariant violated: the sum of x and y must always equal z")`.
Agreed with mds1

2022-11-03 04:06 UTC, odyslam commented on src/tutorials/best-practices.md
> +To test `internal` functions, write a harness contract that inherits from the contract under test (CuT). Harness contracts that inherit from the CuT expose the `internal` functions as `external` ones
I have sort of added ad hoc helper functions inside the test contract. If you mean helper functions in the Contract Under Test (e.h harness), then we should add it as a `workaround_` which is to signify that the function is not normally available to the contract but is added to the harness/mock for utility. 

What do you think @lucas-manuel

2022-11-03 04:08 UTC, odyslam commented on src/tutorials/best-practices.md
> +
Perhaps also add an `address` field to verify the event's origin? TBH I don't do it always cause "ahem", reasons, but I think it should be a best practice.

@lucas-manuel @mds1 

Can't wait for negative assertions (expectNotEmit).

2022-11-03 04:10 UTC, odyslam commented
Okay, @mds1 @lucas-manuel addressed all your comments. I might have bw for the last (Rikard's suggestions).

Can we resolve all that remain and move to ship this? I think it's **excellent** work and tbh I am super excited to get some feedback 🔥

2022-11-03 04:19 UTC, odyslam commented
Should we add something about code coverage? How accurate is it? I haven't used it at all.

2022-11-03 16:33 UTC, mds1 commented on src/tutorials/best-practices.md
> +1. Always use "absolute" paths for imports, i.e. paths relative to the repo root. This makes it easier to see where files are from and reduces churn when moving files around.
There's recently been other reports where using absolute paths breaks intellisense/autocomplete type of IDE features, e.g. https://github.com/foundry-rs/forge-std/pull/206

But yea, I agree with you. Maybe we just document these tradeoffs and devs can make their own decisions?

2022-11-03 16:41 UTC, mds1 commented on src/tutorials/best-practices.md
> +1. Be consistent with test naming, as it's helpful for filtering tests (e.g. for gas reports you might want to filter out revert tests). When combining naming conventions, keep them alphabetical.
> I like being able to test a contract by just adding the --mc argument.

You can still do that, but with just the `--mp` flag instead, e.g. `forge test --mp test/MyContract.t.sol` 😛

> The "describe" is the `test_functionName` that you can visually observe in the final trace, as they will be grouped.

That's true, I think at the end of the day it's largely similar. You can argue that now then you lose a level of hierarchy/flexibility as now your file (`MyContract.t.sol`) only has a single contract (`contract MyContractTest`), so `--mc MyContractTest` and `--mp test/MyContract.t.sol` are equivalent. 

Granted, with this naming convention, I don't think you lose anything since you can still use the `--mt` flag to run all tests for a given function, though I guess you need to be a bit more clever with your regexes to match everything since some are `test_function` and others are `testFuzz_function`

I'm pretty sure the main benefit of the currently documented approach is that small contracts will compile faster, but tbh we probably need to benchmark this to confirm as I'm not 100% confident

> I would suggest: Let's keep the best practice in place and perhaps revise it. TBH, I need to test it extensively before I am comfortable making a suggestion other than what I have used and I like.

This is fair, I'm onboard with this path forward. I think this can be a living document that continually changes, because eth dev evolves fast

2022-11-03 16:43 UTC, mds1 commented on src/tutorials/best-practices.md
> +- Write fork tests to verify the correct behavior with existing deployed contract.
Should we add this info to the doc? I think your previous stance around fork tests is common, and we should convert people 😁

2022-11-03 16:43 UTC, mds1 commented on src/tutorials/best-practices.md
> +1. Don't forget invariant tests! For the assertion string, use a verbose english description of the invariant: `assertEq(x + y, z, "Invariant violated: the sum of x and y must always equal z")`.
Cool, going to mark this resolved then

2022-11-03 16:45 UTC, mds1 commented on src/tutorials/best-practices.md
> +
+1 on negative assertions, that will be useful

> Perhaps also add an `address` field to verify the event's origin

Is this supported? I thought it wasn't yet, and there's an issue here https://github.com/foundry-rs/foundry/issues/2921

2022-11-03 16:46 UTC, mds1 commented
Hmm I don't know, I still see a lot of issues in the repo around coverage so maybe we leave it out for this first version, and add it in the future

2022-11-03 16:47 UTC, mds1 commented on src/tutorials/best-practices.md
> +1. Be consistent with test naming, as it's helpful for filtering tests (e.g. for gas reports you might want to filter out revert tests). When combining naming conventions, keep them alphabetical.
(I think we can consider this resolved from a merge standpoint, and can leave it open to continue discussion if we want)

2022-11-03 19:57 UTC, mds1 commented
Going to leave some comments later today to:
1. Add info per some of the outstanding comments above
2. Mention one more gotcha around scripting (a frontrunning issue, described in https://github.com/foundry-rs/foundry/issues/3589)

Then I'll take it out of draft for final review + merge

2022-11-03 21:42 UTC, mds1 commented on src/tutorials/best-practices.md
> +1. Always use "absolute" paths for imports, i.e. paths relative to the repo root. This makes it easier to see where files are from and reduces churn when moving files around.
Switched to documenting tradeoffs in 935affb

2022-11-03 21:42 UTC, mds1 commented on src/tutorials/best-practices.md
> +- Write fork tests to verify the correct behavior with existing deployed contract.
Added to doc in 935affb

2022-11-03 21:42 UTC, mds1 commented on src/tutorials/best-practices.md
> +
Added info on event testing in 935affb

2022-11-03 21:53 UTC, mds1 commented
Ok added everything in the last two commits, this is ready for final review + merge

2022-11-04 04:01 UTC, odyslam commented on src/tutorials/best-practices.md
> +
@mds1, then why we can pass an address here? 
https://github.com/foundry-rs/forge-std/blob/ff4bf7db008d096ea5a657f2c20516182252a3ed/src/Vm.sol#L182

2022-11-04 05:06 UTC, odyslam commented
@mds1 let's ship this. I have added it to my backlog to view the video sometime in the next few days. Will take notes and revert back.

2022-11-04 16:02 UTC, mds1 commented
Sounds good, deferring to @gakonst @onbjerg @mattsse to review/merge from here

2022-11-06 15:49 UTC, odyslam commented on src/tutorials/best-practices.md
> +
@mds1 I read the source code and indeed it checks for address. I will make a PR

2022-11-07 20:06 UTC, merged

2022-11-07 20:06 UTC, gakonst commented
Really appreciate you guys taking point here. Merged, and let's iterate on it separately.