feat: Add invariant testing [WIP]
foundry-rs/book pull request #760
Opened 2023-01-06 16:00 UTC by lucas-manuel

2023-01-06 17:31 UTC, gakonst commented on .vscode/settings.json
> +{
remove

2023-01-06 20:24 UTC, mds1 reviewed
Love it so far, just took a pass and left some small comments. Think I'll need to see it a bit more fleshed out before coming up with some naming ideas

2023-01-06 20:24 UTC, mds1 commented on projects/invariant_testing/Basic4626Deposit.sol
> +        require(assets_   != uint256(0), "RDT:M:ZERO_ASSETS");
Needs `forge fmt` 😜

2023-01-06 20:24 UTC, mds1 commented on projects/invariant_testing/Basic4626Deposit.sol
> +// ANCHOR: all
What is `ANCHOR: all`?

2023-01-06 20:24 UTC, mds1 commented on projects/invariant_testing/Basic4626Deposit.sol
> +    uint256
I know this is a WIP, just reminder for us tomake sure the code compiles before merging

2023-01-06 20:24 UTC, mds1 commented on src/forge/advanced-testing.md
> +- [Invariant Testing](./invariant-testing.md)
Nit, I'd probably order these as fuzz > invariant > differential. Fuzz is simplest, invariant builds on it and is useful for most people, differential builds on fuzz too but is less commonly needed

2023-01-06 20:24 UTC, mds1 commented on src/forge/invariant-testing.md
> +- `depth`: Number of function calls made in a given `run`. All defined invariants are asserted after each function call is made.
Let's mention how reverted calls are treated within the `depth` counter (I think they are included and still increase depth when set to not fail on reverts?)

2023-01-06 20:24 UTC, mds1 commented on src/forge/invariant-testing.md
> +This is something to be mindful of when designing target contracts, as target contracts with less functions will have each function called more often due to this probability distribution.
We should really fix this, cc @gakonst https://github.com/foundry-rs/foundry/issues/2986

2023-01-06 20:24 UTC, mds1 commented on src/forge/invariant-testing.md
> +    token.totalSupply())
```suggestion
    token.totalSupply()
```

2023-01-06 20:24 UTC, mds1 commented on src/forge/invariant-testing.md
> +It is not recommended to introduce conditional logic into invariant assertions because they have the possibility of introducing false positives because of an incorrect code path.
Can you expand on this, maybe with an example?

2023-01-07 10:14 UTC, gakonst commented on projects/invariant_testing/Basic4626Deposit.sol
> +// ANCHOR: all
This lets us reference the whole file via a template in the book

2023-01-07 10:15 UTC, gakonst commented on src/forge/invariant-testing.md
> +This is something to be mindful of when designing target contracts, as target contracts with less functions will have each function called more often due to this probability distribution.
ACK

2023-01-08 14:41 UTC, lucas-manuel commented on projects/invariant_testing/Basic4626Deposit.sol
> +    uint256
Yeah I'm gonna get rid of this file altogether actually

2023-01-08 14:41 UTC, lucas-manuel commented on src/forge/advanced-testing.md
> +- [Invariant Testing](./invariant-testing.md)
Sounds good will do

2023-01-08 14:42 UTC, lucas-manuel commented on src/forge/invariant-testing.md
> +- `depth`: Number of function calls made in a given `run`. All defined invariants are asserted after each function call is made.
Yeah can mention that

2023-01-23 12:18 UTC, PaulRBerg commented on src/forge/advanced-testing.md
> +- [Invariant Testing](./invariant-testing.md)
I second @mds1's comment - to my shame, this is the first time I hear about differential testing.

2023-01-23 12:21 UTC, PaulRBerg commented on src/forge/invariant-testing.md
> +<td>Query the a protocol smart contract function and compare it against a naive and typically highly gas-inefficient implementation of the same desired logic.</td>
Typo: "the a".

2023-01-23 12:22 UTC, PaulRBerg commented on src/forge/invariant-testing.md
> +Invariants must hold for the course over the course of a given fuzzing campaign, but that doesn't mean they must hold true in every situation. There is the possibility for certain invariants to be in
We should delete "for the course" here.

2023-01-23 13:15 UTC, PaulRBerg commented
I also read through the first draft of this, and I like it a lot - it's straight to the point.

What I think would be very much worth documenting, especially at the beginning of the Markdown document, is the fact that Forge considers all functions that start with `invariant_` an invariant test.

2023-01-24 20:42 UTC, PaulRBerg commented
@lucas-manuel, quick terminology question.

In August 2022, you referred in this [comment](https://github.com/foundry-rs/book/issues/497#issuecomment-1208473205) to the target contracts that encapsulate the calls to the real contracts that are to be invariant tested as "actors".

However, in this PR, it looks like you have changed the name to "handler" - am I correct that you now prefer this terminology over "actor"? If yes, why is it that Maple V2 uses [actors](https://github.com/maple-labs/maple-core-v2/tree/00f01ae7175885f8d49ac201a1c72465e320b2f6/tests/invariants/actors)?

2023-01-25 16:39 UTC, lucas-manuel commented
> @lucas-manuel, quick terminology question.
> 
> In August 2022, you referred in this [comment](https://github.com/foundry-rs/book/issues/497#issuecomment-1208473205) to the target contracts that encapsulate the calls to the real contracts that are to be invariant tested as "actors".
> 
> However, in this PR, it looks like you have changed the name to "handler" - am I correct that you now prefer this terminology over "actor"?

Thats right - we're moving to handlers since the term "actor" was used when we had to use one contract per user, before pranking was possible. Now that multiple actors can be used within a give contract, we determined that handler should be used instead.

2023-01-25 16:44 UTC, lucas-manuel commented on src/forge/invariant-testing.md
> +Invariants must hold for the course over the course of a given fuzzing campaign, but that doesn't mean they must hold true in every situation. There is the possibility for certain invariants to be in
Fixed thanks

2023-01-25 18:03 UTC, PaulRBerg commented
Thanks for confirming, @lucas-manuel.

Speaking of pranking multiple actors - the [`useRandomLp`](https://github.com/maple-labs/maple-core-v2/blob/00f01ae7175885f8d49ac201a1c72465e320b2f6/tests/invariants/actors/LpHandler.sol#L68-L73) modifier used in maple-core-v2 is something that all invariant users may need. I think that it would be worth it to rename it to something more general-purpose (e.g. `useRandomUser` or `useRandomActor`) and ship it with the `InvariantTest` contract part of Forge Std.

2023-01-25 19:35 UTC, PaulRBerg commented
Potentially dumb question - can `vm.assume` be used in invariant tests?

I see no reference to this cheatcode in Lucas' examples, but I'm not sure if this is because Maple uses a different constraining system (`constrictToRange`), or because fuzzing assumptions are not meant to be used in an invariant context. And if not, why? It might be worth it to explain this in the docs.

If I understand this correctly, under "Bounded Testing", the user is expected to bound the inputs to avoid reverts.

2023-01-25 23:15 UTC, pcaversaccio commented on src/forge/invariant-testing.md
> +2. Contracts that are added to the the `targetContracts` array are added to the set of target contracts. (TODO: check if this is possible during invariant campaigns yet)
The current wording is rather confusing (at least for me) - can you please formulate it in a way that people understand that if `targetContracts` method is present on a contract, forge will use the array returned by that method **instead** (and not all contracts in the `setUp` function).

2023-01-26 03:45 UTC, lucas-manuel commented
Gonna work to push this through now, what is missing? @mds1 @gakonst @PaulRBerg @pcaversaccio

2023-01-26 03:45 UTC, lucas-manuel commented
> Potentially dumb question - can `vm.assume` be used in invariant tests?
> 
> I see no reference to this cheatcode in Lucas' examples, but I'm not sure if this is because Maple uses a different constraining system (`constrictToRange`), or because fuzzing assumptions are not meant to be used in an invariant context. And if not, why? It might be worth it to explain this in the docs.
> 
> If I understand this correctly, under "Bounded Testing", the user is expected to bound the inputs to avoid reverts.

Correct me if I'm wrong @mds1 but I believe `vm.assume` would work in the same way as in fuzz tests for this. Haven't used it personally though.

2023-01-26 03:46 UTC, lucas-manuel commented
> Thanks for confirming, @lucas-manuel.
> 
> Speaking of pranking multiple actors - the [`useRandomLp`](https://github.com/maple-labs/maple-core-v2/blob/00f01ae7175885f8d49ac201a1c72465e320b2f6/tests/invariants/actors/LpHandler.sol#L68-L73) modifier used in maple-core-v2 is something that all invariant users may need. We should consider renaming it to something more general-purpose (e.g. `useRandomUser` or `useRandomActor`) and ship it with the `InvariantTest` contract part of Forge Std.

This is an interesting idea, thoughts @mds1 ?

2023-01-26 03:53 UTC, lucas-manuel commented on src/forge/invariant-testing.md
> +2. Contracts that are added to the the `targetContracts` array are added to the set of target contracts. (TODO: check if this is possible during invariant campaigns yet)
Is this the case? I haven't tested this. Updated the wording though let me know if that's better.

2023-01-26 07:39 UTC, pcaversaccio commented on src/forge/invariant-testing.md
> +2. Contracts that are added to the the `targetContracts` array are added to the set of target contracts. (TODO: check if this is possible during invariant campaigns yet)
Well @msd1 told me that yesterday :) so maybe he should confirm as well.

2023-01-26 07:42 UTC, pcaversaccio commented
> Gonna work to push this through now, what is missing? @mds1 @gakonst @PaulRBerg @pcaversaccio 

Proper descriptions on _all_ the invariant helper functions like `targetSender` etc. would be very nice.

2023-01-26 10:44 UTC, PaulRBerg commented
> I believe `vm.assume` would work in the same way as in fuzz tests for this

It doesn't. I'm getting `Failed Assertion` errors if I have `vm.assume` statements in the invariant tests. If this is not intended behavior, should I open an issue in `forge-std`?

> Proper descriptions on all the invariant helper functions

Yes! A markdown table for this would be awesome.

> Gonna work to push this through now, what is missing?

The greatest conceptual leap for me were the handler contracts - I spent a few days looking at the `maple-core-v2` repository, and the [`LoanHandler`][lh] and the [`LpHandler`][lph] contracts were the most difficult to understand.

I see that you added more explanations and a few diagrams about them in the meantime (6 hrs ago), which are awesome. But I think that there are still a few other core concepts that it would be good to document, too:

1. How should actors be generated? This may depend upon the business logic of the smart contract under test, but we should be able to come up with a few rules of thumb, e.g. generate the actors in the constructor and store them in an array.
2. How should actors and other contract storage items be fuzzed? In `maple-core-v2`, you are using these seed arguments (`warpSeed_`, `borrowerIndexSeed_`), and it took me a while to understand their role. It would also be good to mention the need for a `useRandomActor` modifier - at least until Foundry offers a built-in solution for this.
3. Should handler contracts inherit from `Test`? Or `Utils`? If not, how can they get access to `vm`, `bound`, and so forth?

[lh]: https://github.com/maple-labs/maple-core-v2/blob/main/tests/invariants/actors/LoanHandler.sol
[lph]: https://github.com/maple-labs/maple-core-v2/blob/00f01ae7175885f8d49ac201a1c72465e320b2f6/tests/invariants/actors/LpHandler.sol

2023-01-26 14:48 UTC, mds1 commented
> It doesn't. I'm getting `Failed Assertion` errors if I have `vm.assume` statements in the invariant tests. If this is not intended behavior, should I open an issue in `forge-std`?

@PaulRBerg Nice catch, just created https://github.com/foundry-rs/foundry/issues/4190 to track

> Speaking of pranking multiple actors - the [`useRandomLp`](https://github.com/maple-labs/maple-core-v2/blob/00f01ae7175885f8d49ac201a1c72465e320b2f6/tests/invariants/actors/LpHandler.sol#L68-L73) modifier used in maple-core-v2 is something that all invariant users may need. We should consider renaming it to something more general-purpose (e.g. `useRandomUser` or `useRandomActor`) and ship it with the `InvariantTest` contract part of Forge Std.
> 
> > This is an interesting idea, thoughts @mds1 ?

This is an interesting idea. More generally maybe we can add a template `InvariantHandler` contract to forge-std. @lucas-manuel @PaulRBerg if either of you have ideas on what this could look like, create an issue in forge-std and we can continue the conversation there.

> Gonna work to push this through now, what is missing? @mds1 @gakonst @PaulRBerg @pcaversaccio

Awesome, thanks! Later today I'll review what's currently here and reply with some thoughts

2023-01-26 19:00 UTC, PaulRBerg commented
> More generally maybe we can add a template InvariantHandler contract to forge-std.

I like this idea. Definitely one or two helpers for actor generation and management would be nice. I may open an issue for this later.

2023-01-26 23:05 UTC, mds1 commented on src/forge/invariant-testing.md
> +- `depth`: Number of function calls made in a given `run`. All defined invariants are asserted after each function call is made. If a function call reverts, the `depth` counter still increments.
@PaulRBerg do you think this explanation is clear? I know there was some confusion in https://github.com/foundry-rs/foundry/issues/3005 around what a `run` is

2023-01-26 23:06 UTC, mds1 commented on src/forge/invariant-testing.md
> +Invariants are mathematical expressions that should always hold true over the course of a fuzzing campaign. A good invariant testing suite should have as many invariants as possible, and can have dif
They can also be things like "only the owner can do X" which isn't mathematical
 ```suggestion
Invariants are expressions that should always hold true over the course of a fuzzing campaign. A good invariant testing suite should have as many invariants as possible, and can have different testing suites for different protocol states.
```

2023-01-26 23:07 UTC, mds1 commented on src/forge/invariant-testing.md
> +<td>Directly query a protocol smart contracts and assert values are expected.</td>
```suggestion
<td>Directly query a protocol's smart contracts and assert values are expected.</td>
```

2023-01-26 23:08 UTC, mds1 commented on src/forge/invariant-testing.md
> +<td>Naive implementation assertions</td>
Should we call this "Deoptimizing"? It matchings the RV talk's name and is shorter. Or we can write something like 
```suggestion
<td>Deoptimizing (Naive implementation assertions)</td>
```

2023-01-26 23:09 UTC, mds1 commented on src/forge/invariant-testing.md
> +2. Contracts that are added to the the `targetContracts` array are added to the set of target contracts and used instead of the contract deployed in the `setUp`.
Typo. Also are we certain this is true? Ref https://github.com/foundry-rs/foundry/issues/4187
```suggestion
2. Contracts that are added to the the `targetContracts` array are added to the set of target contracts and used instead of the contracts deployed in the `setUp`.
```

2023-01-26 23:11 UTC, mds1 commented on src/forge/invariant-testing.md
> +3. Contracts that are deployed in the `setUp` can be **removed** from the target contracts if they are added to the `excludeContracts` array.
So really, the way you'd use these are:
- Option A: Pair (1) and (3)
- Option B: Use (2)
- Option C: More rare, all 3, if you need to manually add some already-existing contracts from e.g. a fork or `deployCode` usage

If that's correct, would be nice to give those sample use cases

2023-01-26 23:12 UTC, mds1 commented on src/forge/invariant-testing.md
> +pragma solidity ^0.8.7;
May as well use a more recent version for all the pragmas
```suggestion
pragma solidity ^0.8.17;
```

2023-01-26 23:13 UTC, mds1 commented on src/forge/invariant-testing.md
> +By using Handler contracts and **excluding** all protocol contracts from the `targetContracts` array by using the `excludeContracts` function, all function calls made to protocol contracts can be mad
This sentence contradicts the sentence near https://github.com/foundry-rs/book/pull/760/files#r1088430050, i.e. if you use `targetContracts` do you need to also exclude the ones from setup?

2023-01-26 23:15 UTC, mds1 commented on src/forge/invariant-testing.md
> +In addition, with Handlers, input parameters can be bounded to reasonable expected values such that `fail_on_revert` can be set to `true`. This ensures that every function call that is being made by
Let's explicitly call out and link to the `bound` method for this input shaping. And hopefully soon `vm.assume` support too https://github.com/foundry-rs/foundry/issues/4190

2023-01-26 23:16 UTC, mds1 commented on src/forge/invariant-testing.md
> +Another benefit is the ability to perform assertions on function calls as they are happening. An example is asserting the ERC-20 balance of the LP has decremented by `assets` during the `deposit` fun
Demonstrating some patterns like `useRandomUser` and modifying block properties through handler methods would be great to include in this section

2023-01-27 11:15 UTC, PaulRBerg commented on src/forge/invariant-testing.md
> +2. Contracts that are added to the the `targetContracts` array are added to the set of target contracts. (TODO: check if this is possible during invariant campaigns yet)
@lucas-manuel and @pcaversaccio, can confirm that by using `targetContract`, the default behavior of Forge to automatically add all contracts deployed in the `setUp` function is turned off.

2023-01-27 11:17 UTC, pcaversaccio commented on src/forge/invariant-testing.md
> +2. Contracts that are added to the the `targetContracts` array are added to the set of target contracts. (TODO: check if this is possible during invariant campaigns yet)
👍 Awesome - I also tested it and confirm as well - at least with the latest nightly build version.

2023-01-31 13:52 UTC, PaulRBerg commented on src/forge/invariant-testing.md
> +- `depth`: Number of function calls made in a given `run`. All defined invariants are asserted after each function call is made. If a function call reverts, the `depth` counter still increments.
Ye, this is awesome.

2023-01-31 13:56 UTC, PaulRBerg commented on src/forge/invariant-testing.md
> +Invariants are mathematical expressions that should always hold true over the course of a fuzzing campaign. A good invariant testing suite should have as many invariants as possible, and can have dif
I agree with @mds1 that we shouldn't define invariants as exclusively "mathematical expressions", but I don't think that example he gave is fitting in this context.

"only the owner can do X" sounds like a *function-level* invariant to me, whereas Foundry seems to me dealing with *system-level* invariants with its `invariant_` tests (the distinction is nicely explained by Anish Naik [here](https://youtu.be/QofNQxW_K08?t=2840)).

A better example would be time-series types of invariants, e.g. nonces that should only go up incrementally (as discussed in https://github.com/foundry-rs/foundry/issues/3005).

2023-01-31 13:58 UTC, PaulRBerg commented on src/forge/invariant-testing.md
> +2. Contracts that are added to the the `targetContracts` array are added to the set of target contracts and used instead of the contract deployed in the `setUp`.
Ye, we are sure now that `targetContracts` overrides the default behavior to add all contracts from `setUp`.

https://github.com/foundry-rs/foundry/issues/4187#issuecomment-1406356194

2023-01-31 13:59 UTC, PaulRBerg commented on src/forge/invariant-testing.md
> +3. Contracts that are deployed in the `setUp` can be **removed** from the target contracts if they are added to the `excludeContracts` array.
I would bump up Option B and make it the first option mentioned - based on the experience I had with invariant testing so far, it seems to me that this will be the most common way invariant contracts will be targeted.

2023-01-31 13:59 UTC, PaulRBerg commented on src/forge/invariant-testing.md
> +By using Handler contracts and **excluding** all protocol contracts from the `targetContracts` array by using the `excludeContracts` function, all function calls made to protocol contracts can be mad
Nope, you don't.

https://github.com/foundry-rs/foundry/issues/4187#issuecomment-1406356194

2023-01-31 14:01 UTC, PaulRBerg commented on src/forge/invariant-testing.md
> +Another benefit is the ability to perform assertions on function calls as they are happening. An example is asserting the ERC-20 balance of the LP has decremented by `assets` during the `deposit` fun
Example modifier:

```solidity
address[] public actors;
address internal currentActor;

modifier useActor(uint256 actorIndexSeed) {
    currentActor = actors[bound(actorIndexSeed, 0, actors.length - 1)];
    vm.startPrank(currentActor);
    _;
    vm.stopPrank();
}
```

2023-01-31 14:02 UTC, pcaversaccio commented on src/forge/invariant-testing.md
> +3. Contracts that are deployed in the `setUp` can be **removed** from the target contracts if they are added to the `excludeContracts` array.
based on my personal previous experience with dapptools and now Foundry I can share the impression from @PaulRBerg.

2023-01-31 14:19 UTC, pcaversaccio commented
Another input regarding potential examples: it would be good to showcase quickly how to use properly `targetSender` since it might very useful for certain invariant tests. A more sophisticated example where I had to use it for my Vyper contract [`BatchDistributor`](https://github.com/pcaversaccio/snekmate/blob/feat/fuzz-tests/test/utils/BatchDistributor.t.sol#L412):

```solidity
contract BatchDistributorInvariants is Test, InvariantTest {
    VyperDeployer private vyperDeployer = new VyperDeployer();

    IBatchDistributor private batchDistributor;
    BatchDistributorHandler private batchDistributorHandler;

    ERC20Mock private erc20Mock;

    function setUp() public {
        batchDistributor = IBatchDistributor(
            vyperDeployer.deployContract("src/utils/", "BatchDistributor")
        );
        address msgSender = makeAddr("msgSender");
        erc20Mock = new ERC20Mock(
            "MyToken",
            "MTKN",
            msgSender,
            type(uint256).max
        );
        batchDistributorHandler = new BatchDistributorHandler(
            batchDistributor,
            erc20Mock
        );
        targetContract(address(batchDistributorHandler));
        targetSender(msgSender);
    }

    function invariantNoEtherBalance() public {
        assertEq(address(batchDistributor).balance, 0);
    }

    function invariantNoTokenBalance() public {
        /**
         * @dev This invariant breaks when tokens are sent directly to `batchDistributor`
         * as part of `distribute_token`. However, this behaviour is acceptable.
         */
        assertEq(erc20Mock.balanceOf(address(batchDistributor)), 0);
    }
}
```

2023-02-01 01:41 UTC, gakonst requested changes
tiny changes, supportive of all the comments, let's ship this!

2023-02-01 01:41 UTC, gakonst commented on src/forge/invariant-testing.md
> +Invariants are mathematical expressions that should always hold true over the course of a fuzzing campaign. A good invariant testing suite should have as many invariants as possible, and can have dif
```suggestion
Invariants are conditions expressions that should always hold true over the course of a fuzzing campaign. A good invariant testing suite should have as many invariants as possible, and can have different testing suites for different protocol states. Examples of an invariant would be "the xy=k formula always holds" for Uniswap, or "the sum of all owner balances is equal to the total supply" for an ERC20.
```

2023-02-01 01:41 UTC, gakonst commented on src/forge/invariant-testing.md
> +<td>Naive implementation assertions</td>
i like

2023-02-01 01:41 UTC, gakonst commented on src/forge/invariant-testing.md
> +3. Contracts that are deployed in the `setUp` can be **removed** from the target contracts if they are added to the `excludeContracts` array.
+1 I would recommend B more so

2023-02-01 01:41 UTC, gakonst commented on src/forge/invariant-testing.md
> +Another benefit is the ability to perform assertions on function calls as they are happening. An example is asserting the ERC-20 balance of the LP has decremented by `assets` during the `deposit` fun
let's add paul's modifier above^

2023-02-01 22:07 UTC, lucas-manuel commented on src/forge/invariant-testing.md
> +Invariants are mathematical expressions that should always hold true over the course of a fuzzing campaign. A good invariant testing suite should have as many invariants as possible, and can have dif
Changed this to `defined assertions` to be more general, it gets defined more below.

2023-02-01 22:08 UTC, lucas-manuel commented on src/forge/invariant-testing.md
> +Invariants are mathematical expressions that should always hold true over the course of a fuzzing campaign. A good invariant testing suite should have as many invariants as possible, and can have dif
Updated to this

2023-02-01 22:12 UTC, lucas-manuel commented on src/forge/invariant-testing.md
> +<td>Naive implementation assertions</td>
@PaulRBerg https://www.youtube.com/watch?v=ETlNhV9jYJw&t=747s

2023-02-01 22:12 UTC, lucas-manuel commented on src/forge/invariant-testing.md
> +<td>Naive implementation assertions</td>
Update

2023-02-01 22:16 UTC, lucas-manuel commented on src/forge/invariant-testing.md
> +3. Contracts that are deployed in the `setUp` can be **removed** from the target contracts if they are added to the `excludeContracts` array.
Moved around, lmk if this makes sense/should be reworded.

2023-02-02 18:06 UTC, lucas-manuel commented on src/forge/invariant-testing.md
> +pragma solidity ^0.8.7;
Updated

2023-02-02 18:33 UTC, lucas-manuel commented on src/forge/invariant-testing.md
> +By using Handler contracts and **excluding** all protocol contracts from the `targetContracts` array by using the `excludeContracts` function, all function calls made to protocol contracts can be mad
Nice TIL! Updated locally

2023-02-03 11:38 UTC, PaulRBerg commented
Speaking of useful modifiers, something like this may also be worth documenting:

```solidity
mapping(string => uint256) public calls;
uint256 public totalCalls;

modifier instrument(string memory func) {
    calls[func]++;
    totalCalls++;
    _;
}
```

This can be applied to handler contract functions like this:

```solidity
function myFunc() external instrument("myFunc") {
    // ...
}
```

The purpose being to get a call summary (e.g. [here][1]).

However, I am not sure whether adding a note about the above is worth it given the intention to add native support for instrumentation in Foundry (https://github.com/foundry-rs/foundry/issues/3607).

[1]: https://github.com/lucas-manuel/invariant-examples/blob/d6b4f06d7ebe0bbaebcfd666fb00433d30ab28da/test/WrappedTests.t.sol#L87-L101

2023-02-04 08:12 UTC, giovannidisiena commented on src/forge/invariant-testing.md
> +This setup will call `foo.addToA()` and `foo.addToB()` with a 50%-50% probability distribution with fuzzed inputs. Inevitably, the inputs will start to cause overflows and the function calls will sta
Excellent documentation @lucas-manuel, thank you! I believe the default configuration here is `fail_on_revert = false` as per the [config README](https://github.com/foundry-rs/foundry/blob/master/config/README.md?plain=1#L183) which makes more sense in the context of this sentence and the final handler section.

2023-02-05 03:37 UTC, gakonst commented
@lucas-manuel I think one final pass based on the above comments and we're good to merge as a first iteration

2023-02-06 01:30 UTC, pcaversaccio commented
Haven't checked again the content of this PR but apparently you thought it would be a good idea to rename `InvariantTest` but `StdInvariant` (https://github.com/foundry-rs/forge-std/commit/b4f121555729b3afb3c5ffccb62ff4b6e2818fd3). Broke all of my invariant tests in the CI lol - in any case if we somewhere use the old term `InvariantTest` this should be updated.

2023-02-06 07:21 UTC, PaulRBerg commented
@pcaversaccio you should set the `branch` to `v1` in your `.gitmodules` (https://github.com/foundry-rs/forge-std/issues/275).

Nonetheless, I agree with you that all references to `InvariantTest` should be changd to `SdInvariant`.

2023-02-06 08:37 UTC, pcaversaccio commented
@PaulRBerg yeah agreed - however in my particular case here I didn't want to pin to v1 since the development iterations where important to me (i.e. invariant testing) and therefore I always pulled directly the `main` branch every two days or so. That's why I immediately realised that something is broken. But generally the pinning strategy you're suggesting is also something I usually follow.

2023-02-06 09:24 UTC, pcaversaccio commented
Also, I quickly wanted to emphasise that people should know that `Test` inherits from it _by default_ now. Because if you do the following `MyContract is Test, StdInvariant {...}` it will not compile due to the linearisation patter by Solidity. However, folks will read the release of `forge-std` and will get confused:
![image](https://user-images.githubusercontent.com/25297591/216934084-9bfb212e-782e-44d7-930e-ca23d972bb48.png)

2023-02-06 16:22 UTC, lucas-manuel commented
> Speaking of useful modifiers, something like this may also be worth documenting:
> 
> ```solidity
> mapping(string => uint256) public calls;
> uint256 public totalCalls;
> 
> modifier instrument(string memory func) {
>     calls[func]++;
>     totalCalls++;
>     _;
> }
> ```
> 
> This can be applied to handler contract functions like this:
> 
> ```solidity
> function myFunc() external instrument("myFunc") {
>     // ...
> }
> ```
> 
> The purpose being to get a call summary (e.g. [here](https://github.com/lucas-manuel/invariant-examples/blob/d6b4f06d7ebe0bbaebcfd666fb00433d30ab28da/test/WrappedTests.t.sol#L87-L101)).
> 
> However, I am not sure whether adding a note about the above is worth it given the intention to add native support for instrumentation in Foundry ([foundry-rs/foundry#3607](https://github.com/foundry-rs/foundry/issues/3607)).

I like this idea but yeah I think we should push for the native support, thoughts @mds1 @gakonst ?

2023-02-06 16:26 UTC, mds1 commented
> However, folks will read the release of forge-std and will get confused

The screenshot is correct when using v1.3.0 of forge-std, when v1.4.0 is released the release notes will document the breaking change and new usage info.

I agree with updating the docs to reflect this upcoming usage / naming though, cc @lucas-manuel 

> I like this idea but yeah I think we should push for the native support, thoughts @mds1 @gakonst ?

Agreed native support is preferable. There may be higher priority fixes/features though so I do think a template handler contract / modifiers in forge-std would be useful in the meantime. I also like [this pattern](https://twitter.com/eth_call/status/1622321144756928512) that I recently came across from @horsefacts, and people can then implement their own getters to parse the calldata

2023-02-06 16:28 UTC, lucas-manuel commented
> > However, folks will read the release of forge-std and will get confused
> 
> The screenshot is correct when using v1.3.0 of forge-std, when v1.4.0 is released the release notes will document the breaking change and new usage info.
> 
> I agree with updating the docs to reflect this upcoming usage / naming though, cc @lucas-manuel
> 
> > I like this idea but yeah I think we should push for the native support, thoughts @mds1 @gakonst ?
> 
> Agreed native support is preferable. There may be higher priority fixes/features though so I do think a template handler contract / modifiers in forge-std would be useful in the meantime. I also like [this pattern](https://twitter.com/eth_call/status/1622321144756928512) that I recently came across from @horsefacts, and people can then implement their own getters to parse the calldata

Should I add these to the docs?

2023-02-06 16:55 UTC, lucas-manuel commented
Just adding the target definitions and will push for final review.

2023-02-06 17:29 UTC, lucas-manuel commented
Alright good for review 👍

2023-02-06 17:32 UTC, horsefacts commented
> horsefact's pattern is still not too common so I'd avoid including it

Agree, this is more an exploration than something I'd recommend right now.

2023-02-06 17:57 UTC, mds1 commented on src/forge/invariant-testing.md
> +- *"The sum of all owner balances is equal to the total supply"* for an ERC-20 token.
Nit, since "owner" sounds like a privileged actor 
```suggestion
- *"The sum of all user balances is equal to the total supply"* for an ERC-20 token.
```

2023-02-06 18:02 UTC, mds1 commented on src/forge/invariant-testing.md
> +This setup will call `foo.addToA()` and `foo.addToB()` with a 50%-50% probability distribution with fuzzed inputs. Inevitably, the inputs will start to cause overflows and the function calls will sta
Yea @lucas-manuel `false` is the default here

https://github.com/foundry-rs/foundry/blob/4718a390de2afc7372082d77afe7dc8d0e435215/config/src/invariant.rs#L31

2023-02-06 18:27 UTC, lucas-manuel commented
> One comment [here](https://github.com/foundry-rs/book/pull/760#discussion_r1097742845) we should fix, but otherwise this looks really great! Awesome job @lucas-manuel 🔥

Updated! 👍

2023-02-08 21:57 UTC, mds1 commented
@gakonst @lucas-manuel anything blocking merge here?

think we might just need info around how `targetContracts` can change since it automatically adds contracts deployed during an invariant run, cc @joshieDo for details

2023-02-09 01:45 UTC, lucas-manuel commented
> @gakonst @lucas-manuel anything blocking merge here?
> 
> think we might just need info around how `targetContracts` can change since it automatically adds contracts deployed during an invariant run, cc @joshieDo for details

Good to go on my end

2023-02-09 10:38 UTC, PaulRBerg requested changes
Just had a final read, looks lit. Thanks again @lucas-manuel for writing this up. There are only a few minor typos - besides these, LGTM.

I'm glad to see the `useActor` modifier included in this PR 🙌

2023-02-09 10:38 UTC, PaulRBerg commented on src/forge/invariant-testing.md
> +| `targetArtifact(string memory newTargetedArtifact_)` | Adds a given string to the to the `_targetedArtifacts` array. This set of strings is used for the target artifacts.  |
Double `to the to the` typo.

2023-02-09 10:38 UTC, PaulRBerg commented on src/forge/invariant-testing.md
> +1. Contracts that are manually added to the the `targetContracts` array are added to the set of target contracts.
Double `the the` typo.

2023-02-09 10:50 UTC, pcaversaccio reviewed
Fixed typo: explictly ==> explicitly & I think `:` makes more sense where I suggested it. Anything else LGTM.

![image](https://user-images.githubusercontent.com/25297591/217792041-10d261ec-577b-4cd8-9391-0cabc3075cac.png)

2023-02-09 10:50 UTC, pcaversaccio commented on src/forge/invariant-testing.md
> +Invariant testing campaigns have two dimensions, `runs` and `depth`.
```suggestion
Invariant testing campaigns have two dimensions, `runs` and `depth`:
```

2023-02-09 10:50 UTC, pcaversaccio commented on src/forge/invariant-testing.md
> +| `excludeSender(address newExcludedSender_)` | Adds a given address to the to the `_excludedSenders` array. This set of addresses is explictly excluded from the target senders. |
```suggestion
| `excludeSender(address newExcludedSender_)` | Adds a given address to the to the `_excludedSenders` array. This set of addresses is explicitly excluded from the target senders. |
```

2023-02-09 10:50 UTC, pcaversaccio commented on src/forge/invariant-testing.md
> +| `excludeArtifact(string memory newExcludedArtifact_)` | Adds a given string to the to the `_excludedArtifacts` array. This set of strings is explictly excluded from the target artifacts. |
```suggestion
| `excludeArtifact(string memory newExcludedArtifact_)` | Adds a given string to the to the `_excludedArtifacts` array. This set of strings is explicitly excluded from the target artifacts. |
```

2023-02-09 16:43 UTC, lucas-manuel commented
Made all requested changes thanks @PaulRBerg @pcaversaccio

2023-02-10 20:10 UTC, gakonst commented
let's send it

2023-02-10 20:10 UTC, merged