add: 📽️ Youtube playlists for learning foundry
foundry-rs/book pull request #914
Opened 2023-06-07 21:38 UTC by m0ham3dx

Addition of youtube playlists for learning Foundry , beginner to advanced

2023-06-07 21:41 UTC, Evalir requested changes
this looks good to me pending nit, wdyt @mds1 ?

2023-06-07 21:41 UTC, Evalir commented on src/tutorials/learn-foundry.md
> +Unofficial *youtube playlists* of Foundry tutorials from famousblockchain tutorial makers.
```suggestion
Unofficial *youtube playlists* of Foundry tutorials from Blockchain educators.
```

2023-06-07 21:54 UTC, m0ham3dx commented on src/tutorials/learn-foundry.md
> +Unofficial *youtube playlists* of Foundry tutorials from famousblockchain tutorial makers.
Thanks for the correction , i see you've already made the change so I dont have to make another PR to this

2023-06-07 21:59 UTC, m0ham3dx commented on src/tutorials/learn-foundry.md
> +Unofficial *youtube playlists* of Foundry tutorials from famousblockchain tutorial makers.
Ok thanks for already applying the changes, was a little confusing for me that I had to make another commit to this pr , and added the earlier message which i deleted

2023-06-08 10:05 UTC, mattsse approved these changes
nice

2023-06-08 10:05 UTC, merged