[DO NOT MERGE] feat(`v1`): Migration guide
foundry-rs/book pull request #922
Opened 2023-06-16 04:47 UTC by Evalir

This PR contains the migration guide for V1. It contains:
- A guide on how to upgrade foundry locally to V1
- A list of deprecated features
- A list of non-breaking changes that are important to know
- A list of breaking changes, and how to tackle them
- Recommended tips for managing the migration.

I expect to flesh out more content on this over the next few days to make it more thorough, but I believe this draft covers enough for us to start discussing.

2023-06-16 05:02 UTC, Evalir reviewed
a small self-review

note that i haven't done a grammar check on this yet. will do so tomorrow

2023-06-16 05:02 UTC, Evalir commented on src/getting-started/migrating-to-v1.md
> +### Recommended approach for tackling codebase migrations
I think adding bite-sized pieces of before/after test cases would be cool

2023-07-04 00:41 UTC, mds1 reviewed
Didn't finish reviewing yet but here's the first batch of comments. Really great overall so far though, will finish giving this a read tomorrow

2023-07-04 00:41 UTC, mds1 commented on src/migrating-to-v1/breaking-changes.md
> +- it now only works for the _next call_. This means if you used to declare all your expected emits at the top of the test, you may now have to move them to just before the next call you perform. Chea
two small changes, first one is the same in both suggestions, second one differs a bit
```suggestion
- It now only works for the _next call_. This means if you used to declare all your expected emits at the top of the test, you may now have to move them to just before the next call you perform. Cheatcode calls are ignored. As long as the events are emitted within the next call's context, they will be matched.
```
```suggestion
- It now only works for the _next call_. This means if you used to declare all your expected emits at the top of the test, you may now have to move them to just before the next call you perform. Cheatcode calls are ignored. As long as the events are emitted during the next call's execution, they will be matched.
```

2023-07-04 00:41 UTC, mds1 commented on src/migrating-to-v1/breaking-changes.md
> +    event E(uint256 indexed e);
Nit, but maybe make the events a bit different to ensure no one gets confused by thinking this only applies in cases like this where everything is indexed or something
```suggestion
    event A(uint256 indexed a);
    event B(uint256 b);
    event C(address indexed c1, uin256 c2);
    event D(bytes32 d1, uint256 d2, address indexed d3);
    event E(uint256 indexed e);
```

2023-07-04 00:41 UTC, mds1 commented on src/migrating-to-v1/breaking-changes.md
> +        cheats.expectEmit(true, false, false, true);
Should we `vm` here instead? I think the book may be inconsistent and use both, but `vm` is more common IME
```suggestion
        vm.expectEmit(true, false, false, true);
```

2023-07-04 00:41 UTC, mds1 commented on src/migrating-to-v1/breaking-changes.md
> +    /// this passes.
Same for other "this passes" comments, just capitalizing since it's a new sentence. Let's also use `//` since there are regular non-natspec comments
```suggestion
    // This passes.
```

2023-07-04 00:41 UTC, mds1 commented on src/migrating-to-v1/breaking-changes.md
> +        cheats.expectEmit(true, false, false, true);
We should also mix things up with the `expectEmit` args a bit, and show the `vm.expectEmit()` syntax too

2023-07-04 00:41 UTC, mds1 commented on src/migrating-to-v1/breaking-changes.md
> +    /// Calling a contract function internally is a JUMPI, not a call,
This is probably just a `JUMP` not a `JUMPI` since there's no conditional

2023-07-04 00:41 UTC, mds1 commented on src/migrating-to-v1/breaking-changes.md
> +    function declareExpectedEvents() internal {
We should also have an incorrect example of e.g. a library function / free function where the event is emitted within the test contract and therefore can't be caught

2023-07-04 00:41 UTC, mds1 commented on src/migrating-to-v1/breaking-changes.md
> +#### `expectEmit`
Adding a table of contents so we can jump to different sections on this page would be nice

2023-07-04 00:41 UTC, mds1 commented on src/migrating-to-v1/breaking-changes.md
> +    Protocol public protocol;
Seems we never initialize this variable anywhere

2023-07-04 13:37 UTC, mds1 commented on src/migrating-to-v1/breaking-changes.md
> +    function declareExpectedEvents() internal {
Ah it seems you have a section for this later, though it's only for expectCall/Revert, not Emit. Maybe include expectEmit in that section too and link to it in each of the prior expectCall/Revert/Emit sections?

2023-07-04 13:37 UTC, mds1 commented on src/migrating-to-v1/deprecated-features.md
> +### Deprecating testFail
```suggestion
### `testFail`
```

2023-07-04 13:37 UTC, mds1 commented on src/migrating-to-v1/deprecated-features.md
> +The now-recommended pattern is to refactor the actions that will make your test revert and subsequently fail in an utility function, and use `expectRevert` to ensure that this function call failed. T
Similarly, I think this has always been recommended. And we can simplify this a bit since the "refactor" part may not be necessary and has already been covered in the expectRevert section
```suggestion
A better pattern is to use `expectRevert` to ensure that a function call reverted in a specific way. This way, the test failure is expected explicitly, removing the possibility that the test fails in an unintended, undetectable way.
```

2023-07-04 13:37 UTC, mds1 commented on src/migrating-to-v1/deprecated-features.md
> +    function testReverterReverts() public {
We should also start making sure the test names in these code snippets match what's in the best practices page, for consistency
```suggestion
    function test_RevertIf_AlwaysReverts() public {
```

2023-07-04 13:37 UTC, mds1 commented on src/migrating-to-v1/deprecated-features.md
> +        vm.expectRevert();
let's avoid using the empty args version in the examples, since (like `testFail`) this is weaker and should only be used when necessary

2023-07-04 13:37 UTC, mds1 commented on src/migrating-to-v1/deprecated-features.md
> +It is now impossible to use the following cheatcodes on precompiles: `etch`, `load`, `store`, `deal`.
let's add rationale as to why

2023-07-04 13:37 UTC, mds1 commented on src/migrating-to-v1/migrating-to-v1.md
> +Foundry V1 is the blazing-fast smart contract testing framework you already know, but finally marked as stable and respecting semver. It's the culmination of over a year of work and more than 200 con
```suggestion
Foundry V1 is the blazing-fast smart contract testing framework you already know, but finally marked as stable and respecting [semver](https://semver.org/). It's the culmination of over a year of work and more than 200 contributors that made it happen.
```

2023-07-04 13:37 UTC, mds1 commented on src/migrating-to-v1/migrating-to-v1.md
> +V1 mainly brings more strictness to several cheatcodes, which will be the main thing to migrate early on. While we recommend migrating as soon as possible to V1, It's possible to upgrade your local i
link to docs on how to do what's suggested in that second paragraph? I'm a bit confused on that because wouldn't the nightlies just become the v1 version that have breaking changes? I'd have thought you need to pin CI to a pre-v1 nightly
```suggestion
V1 mainly increases the strictness of several cheatcodes, and accommodating this is the primary change required to migrate to V1. We recommend migrating to V1 as soon as possible, as the stricter cheats may reveal bugs or issues in your code and test suite. 

If migration is time consuming, you can consider upgrading your local foundry installation while migrating tests, but maintaining nightly usage on CI to avoid any failures that might disrupt your workflow.
```

2023-07-04 13:37 UTC, mds1 commented on src/migrating-to-v1/migrating-to-v1.md
> +The [dev Telegram](https://t.me/foundry_rs) is available for any concerns you may have that are not covered in this guide.
should we link to the support telegram here instead? or maybe both and specify when to use which

2023-07-04 13:37 UTC, mds1 commented on src/migrating-to-v1/non-breaking-changes.md
> +- Snapshot failures between fuzz runs are now persisted, so workarounds are not needed anymore.
what does this mean? maybe we should link to issues/PRs here for more context

2023-07-04 13:37 UTC, mds1 commented on src/migrating-to-v1/non-breaking-changes.md
> +- Sensitive broadcast logs are now logged into the `.gitignore`d `cache` directory, instead of written to logs.
```suggestion
- Sensitive broadcast logs are now logged into the `.gitignore`d `cache` directory, instead of being included in the broadcast files that are intended to be committed.
```

2023-07-04 13:37 UTC, mds1 commented on src/migrating-to-v1/upgrading-to-v1.md
> +This will reinstall `foundryup`. You can then run `foundryup` on your terminal to download the latest `V1` version.
style nit: we use `V1` everywhere, do we prefer this or `v1`? I'm indifferent but usually use lowercase

2023-07-04 13:37 UTC, mds1 commented on src/migrating-to-v1/upgrading-to-v1.md
> +When it comes to CI, you can add a `version` input field with `v1.0.0` or your desired stable release. This will pin the CI to that stable version.
does this support ways to specify a range of versions, e.g. `v1` to always use the latest `v1.x.y` release? we definitely should support something like that, which is common for github actions

2023-07-06 14:34 UTC, Evalir commented on src/migrating-to-v1/upgrading-to-v1.md
> +When it comes to CI, you can add a `version` input field with `v1.0.0` or your desired stable release. This will pin the CI to that stable version.
Ah, not really—but we could add this and release a new CI toolchain version.

2023-07-07 19:59 UTC, lucas-manuel requested changes

2023-07-07 19:59 UTC, lucas-manuel commented on src/migrating-to-v1/breaking-changes.md
> +        vm.expectEmit(true, false, false, true);
Not a breaking change though so all good if its not included

2023-07-07 19:59 UTC, lucas-manuel commented on src/migrating-to-v1/breaking-changes.md
> +// intermediate "mock" contract that calls the library function
Intermediate

2023-07-07 19:59 UTC, lucas-manuel commented on src/migrating-to-v1/deprecated-features.md
> +### Removing the Invariant keyword
`invariant` prefix?

2023-07-07 19:59 UTC, lucas-manuel commented on src/migrating-to-v1/deprecated-features.md
> +    function test_RevertIf_AlwaysReverts() public {
`test_revertIf`..

2023-07-07 19:59 UTC, lucas-manuel commented on src/migrating-to-v1/deprecated-features.md
> +        vm.expectRevert("This reverts);
"This reverts"

2023-07-07 19:59 UTC, lucas-manuel commented on src/migrating-to-v1/deprecated-features.md
> +With foundry v1, we've started deprecating features that are considered anti-patterns or might be misleading and confusing for developers. Deprecated means that while you can continue using these fea
Foundry

2023-07-07 19:59 UTC, lucas-manuel commented on src/migrating-to-v1/migrating-to-v1.md
> +Aside from this, V1 is still the same Foundry you know.
v1

2023-07-07 19:59 UTC, lucas-manuel commented on src/migrating-to-v1/non-breaking-changes.md
> +- `vm.startPrank` now overwrites the existing prank instead of just erroring. However, the already set prank must be used first.
`However, the already set prank must be used first.` this sentence wasn't immediately clear to me, what does this mean?

2023-07-07 19:59 UTC, lucas-manuel commented on src/migrating-to-v1/upgrading-to-v1.md
> +This will reinstall `foundryup`. You can then run `foundryup` on your terminal to download the latest `V1` version.
We should standardize `V1`, V1 and v1. I'm indifferent as to which but should be the same across the docs.

2023-07-07 21:00 UTC, Evalir commented on src/migrating-to-v1/upgrading-to-v1.md
> +This will reinstall `foundryup`. You can then run `foundryup` on your terminal to download the latest `V1` version.
Agreed. My pick is v1—but wdyt @gakonst ? needs to align with blog post.

2023-07-07 21:02 UTC, Evalir commented on src/migrating-to-v1/non-breaking-changes.md
> +- `vm.startPrank` now overwrites the existing prank instead of just erroring. However, the already set prank must be used first.
Hmm, I believe this might be an undocumented, somewhat recent change on startPrank—when this overwrite change was made, i believe the rule is now that if the prank has not been used, it will error. if it has been used, it will overwrite the existing prank. 

so essentially before overwriting the prank you need to use it first

2023-07-07 21:10 UTC, Evalir commented on src/migrating-to-v1/deprecated-features.md
> +With foundry v1, we've started deprecating features that are considered anti-patterns or might be misleading and confusing for developers. Deprecated means that while you can continue using these fea
Done in https://github.com/foundry-rs/book/pull/922/commits/0622765622b80670ca2b838eff1b368440516b65

2023-07-07 21:10 UTC, Evalir commented on src/migrating-to-v1/migrating-to-v1.md
> +Aside from this, V1 is still the same Foundry you know.
Done in https://github.com/foundry-rs/book/pull/922/commits/0622765622b80670ca2b838eff1b368440516b65

2023-07-07 21:10 UTC, Evalir commented on src/migrating-to-v1/deprecated-features.md
> +    function test_RevertIf_AlwaysReverts() public {
Done in https://github.com/foundry-rs/book/pull/922/commits/0622765622b80670ca2b838eff1b368440516b65

2023-07-07 21:10 UTC, Evalir commented on src/migrating-to-v1/deprecated-features.md
> +### Removing the Invariant keyword
Done in https://github.com/foundry-rs/book/pull/922/commits/0622765622b80670ca2b838eff1b368440516b65

2023-07-07 21:10 UTC, Evalir commented on src/migrating-to-v1/breaking-changes.md
> +// intermediate "mock" contract that calls the library function
Done in https://github.com/foundry-rs/book/pull/922/commits/0622765622b80670ca2b838eff1b368440516b65

2023-07-07 21:11 UTC, Evalir commented on src/migrating-to-v1/deprecated-features.md
> +        vm.expectRevert("This reverts);
Done in https://github.com/foundry-rs/book/pull/922/commits/0622765622b80670ca2b838eff1b368440516b65

great catch!

2023-07-07 21:22 UTC, Evalir commented on src/migrating-to-v1/breaking-changes.md
> +        vm.expectEmit(true, false, false, true);
it's a good suggestion! added the refresher here: https://github.com/foundry-rs/book/pull/922/commits/9f67b28d479691c83c76fd0832173d196dcfb109

2023-07-07 22:56 UTC, mds1 commented on src/migrating-to-v1/deprecated-features.md
> +    function test_RevertIf_AlwaysReverts() public {
The best practices page of the book uses `test_RevertIf_AlwaysReverts` style though

2023-07-14 10:36 UTC, thedavidmeister commented
please reconsider the changes to `expectRevert` being unable to test reverts behind a jump

or provide some functionality that allows me to specify the depth, if the intent is to be more strict i'm happy to be more explicit

2025-03-31 16:14 UTC, Evalir commented
Should this be closed? @zerosnacks

2025-04-01 07:56 UTC, closed without merging